import { jsPDF } from "jspdf";
import { imageFormatFromDataUrl } from "../data/branding";

export type ReportBrand = {
  agencyName: string;
  logoDataUrl?: string | null;
};

function drawTextBrand(doc: jsPDF, brand: ReportBrand, margin: number, y: number) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(47, 70, 48);
  doc.text("COMPLYRER", margin, y);
  doc.setTextColor(36, 30, 24);
  doc.setFontSize(10);
  doc.text(brand.agencyName, margin, y + 14);
  return y + 28;
}

export function startBrandedDoc(
  title: string,
  brand: ReportBrand,
  margin = 48,
) {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  let y = 52;
  const logo = brand.logoDataUrl;
  if (logo) {
    try {
      doc.addImage(logo, imageFormatFromDataUrl(logo), margin, y - 8, 40, 40);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(36, 30, 24);
      doc.text(brand.agencyName, margin + 52, y + 8, { maxWidth: 460 });
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(95, 81, 69);
      doc.text("Prepared with Complyrer", margin + 52, y + 24);
      y += 48;
    } catch {
      y = drawTextBrand(doc, brand, margin, y);
    }
  } else {
    y = drawTextBrand(doc, brand, margin, y);
  }
  doc.setTextColor(36, 30, 24);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  const titleLines = doc.splitTextToSize(title, 514);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 18 + 8;
  return { doc, margin, y };
}

/**
 * Stamp "Digital record generated by Complyrer" (+ document id / timestamp
 * when supplied) into the footer of every page. Call at the end of each PDF
 * builder, after all content is laid out.
 */
export function stampRecordMark(
  doc: jsPDF,
  opts: { documentId?: string; generatedAt?: string | null; margin?: number } = {},
) {
  const margin = opts.margin ?? 48;
  const parts = ["Digital record generated by Complyrer"];
  if (opts.documentId) parts.push(opts.documentId);
  if (opts.generatedAt) parts.push(opts.generatedAt);
  const text = parts.join(" \u00b7 ");
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(150, 138, 124);
    doc.text(text, margin, 768);
    doc.setTextColor(36, 30, 24);
  }
}
