import { test } from "node:test";
import assert from "node:assert/strict";
import { buildCarePlanPdf } from "./carePlanPdf";

test("care plan cover PDF renders identity fields and a reviewed-by completion area", () => {
  const doc = buildCarePlanPdf({
    agencyName: "Evergreen Care",
    individualName: "Ellis Hart",
    title: "Person-Centered Support Plan",
    versionLabel: "v3",
    effectiveOn: "2026-09-01",
  });
  const blob = doc.output("blob") as Blob;
  assert.ok(blob.size > 1000, `expected a real PDF, got ${blob.size} bytes`);
  const text = doc.output() as string;
  assert.ok(text.includes("Person-Centered Support Plan"), "title");
  assert.ok(text.includes("Evergreen Care"), "agency");
  assert.ok(text.includes("Ellis Hart"), "individual");
  assert.ok(text.includes("v3"), "version label");
  assert.ok(text.includes("Reviewed by"), "completion section");
  assert.ok(text.includes("Signature"), "signature line label");
  assert.ok(
    text.includes("Digital record generated by Complyrer"),
    "record mark",
  );
});
