import { test } from "node:test";
import assert from "node:assert/strict";
import { seedRequirements } from "../domain";
import {
  buildComplianceReportPdf,
  complianceReportPdfName,
} from "./complianceReportPdf";

const BASE = {
  agencyName: "Evergreen Care",
  reportDate: "September 14, 2026",
  asOfDate: "2026-09-14",
  siteFilter: "All sites",
  score: 73,
  total: 22,
  done: 16,
  overdue: 3,
  dueSoon: 3,
  review: 2,
  requirements: seedRequirements,
};

test("compliance report PDF includes scores, site mix, status sections, and register", () => {
  const doc = buildComplianceReportPdf(BASE);
  const blob = doc.output("blob") as Blob;
  assert.ok(blob.size > 3000, `expected a real PDF, got ${blob.size} bytes`);
  const text = doc.output() as string;
  assert.ok(text.includes("Evergreen Care"), "agency name");
  assert.ok(text.includes("September 14, 2026"), "report date");
  assert.ok(text.includes("All sites"), "filter context");
  assert.ok(text.includes("2026-09-14"), "as-of date");
  assert.ok(text.includes("Executive Summary"), "summary");
  assert.ok(text.includes("Breakdown by site"), "site breakdown");
  assert.ok(text.includes("Maple House"), "maple in site table");
  assert.ok(text.includes("Oakwood House"), "oakwood in site table");
  assert.ok(text.includes("Compliant summary"), "compliant section");
  assert.ok(text.includes("Requirements register"), "full register");
  assert.ok(text.includes("Pending review"), "review count");
  assert.ok(
    text.includes("Digital record generated by Complyrer"),
    "record mark",
  );
  assert.ok(
    !text.includes("ILLUSTRATIVE DEMO"),
    "production export has no demo watermark",
  );
});

test("demo Mode stamps an illustrative watermark", () => {
  const doc = buildComplianceReportPdf({ ...BASE, demoMode: true });
  const text = doc.output() as string;
  assert.ok(text.includes("ILLUSTRATIVE DEMO"), "demo watermark");
});

test("filename is Agency-compliance-YYYY-MM-DD.pdf", () => {
  assert.equal(
    complianceReportPdfName("Evergreen Care", "2026-09-14T12:00:00.000Z"),
    "Evergreen-Care-compliance-2026-09-14.pdf",
  );
});
