import { test } from "node:test";
import assert from "node:assert/strict";
import { emptyProfile } from "../data/planStack";
import {
  buildConsultationPacketPdf,
  consultationPacketFileName,
} from "./consultationPacketPdf";

const appointment = {
  id: "appt-1",
  agencyId: "a1",
  individualId: "i1",
  startsOn: "2026-09-22",
  startTime: "09:30",
  endTime: "10:15",
  timezone: "America/Chicago",
  consultant: "Dr. Priya Shah",
  specialty: "Neurology",
  reason: "Seizure follow-up",
  visitAddress: "3201 Pompey Drive",
  createdBy: "u1",
  createdByName: "Cameron Price",
  createdAt: "2026-09-10T14:00:00.000Z",
  updatedBy: "",
  updatedByName: "",
  updatedAt: "2026-09-10T14:00:00.000Z",
  deletedBy: "",
  deletedByName: "",
  deletedAt: null,
  completedBy: "",
  completedByName: "",
  completedAt: null,
  visitComments: "",
  consultationFileId: null,
};

test("consultation packet names the Individual and leaves missing fields blank on purpose", () => {
  const profile = {
    ...emptyProfile({
      id: "i1",
      agencyId: "a1",
      siteId: "s1",
      fullName: "Ellis Hart",
      dateOfBirth: "1984-03-12",
    }),
    dmhId: "110245",
    medicaidStatus: "yes" as const,
    specializedDiet: "No concentrated sweets",
    specializedMedical: "Seizure protocol",
    address: "3201 Pompey Drive",
    allergies: [
      { allergen: "Tree nuts", reaction: "Noted on diet order", status: "active" as const },
    ],
  };
  const doc = buildConsultationPacketPdf({
    agencyName: "Evergreen Care",
    individualName: "Ellis Hart",
    dateOfBirth: "1984-03-12",
    siteName: "Cedar House",
    programName: "Residential services",
    profile,
    appointment,
    medications: [{ name: "Levetiracetam", strength: "500 mg" }],
    generatedByName: "Sarah Mitchell",
    generatedAt: "2026-09-12T18:00:00.000Z",
  });
  const blob = doc.output("blob") as Blob;
  assert.ok(blob.size > 2000, `expected a real PDF, got ${blob.size} bytes`);
  const text = doc.output() as string;
  assert.ok(text.includes("Consultation"), "title");
  assert.ok(text.includes("Evergreen Care"), "agency");
  assert.ok(text.includes("Ellis Hart"), "individual");
  assert.ok(text.includes("110245"), "DMH id");
  assert.ok(text.includes("Dr. Priya Shah"), "consultant");
  assert.ok(text.includes("Levetiracetam"), "med name");
  assert.ok(text.includes("500 mg"), "med strength");
  assert.ok(text.includes("Tree nuts"), "allergies from profile");
  assert.ok(text.includes("Not on file"), "honest blanks");
  assert.ok(text.includes("Medicare member number"), "medicare gap labeled");
  assert.ok(text.includes("Generated by Sarah Mitchell"), "generated-by footer");
  assert.ok(
    text.includes("Digital record generated by Complyrer"),
    "record mark",
  );
  assert.ok(!text.includes("people"), "no people noun");
  assert.ok(!text.includes("client"), "no client noun");
});

test("consultation packet filename uses the Individual and date", () => {
  assert.equal(
    consultationPacketFileName("Ellis Hart", "2026-09-22"),
    "complyrer-consultation-ellis-hart-2026-09-22.pdf",
  );
});

test("consultation packet labels allergies as not on file when the list is empty", () => {
  const profile = emptyProfile({
    id: "i1",
    agencyId: "a1",
    siteId: "s1",
    fullName: "Ellis Hart",
    dateOfBirth: "1984-03-12",
  });
  const doc = buildConsultationPacketPdf({
    agencyName: "Evergreen Care",
    individualName: "Ellis Hart",
    dateOfBirth: "1984-03-12",
    siteName: "Cedar House",
    programName: "Residential services",
    profile,
    appointment,
    medications: [],
    generatedByName: "Cameron Price",
    generatedAt: "2026-09-12T18:00:00.000Z",
  });
  const text = doc.output() as string;
  assert.ok(text.includes("Allergies"));
  assert.ok(text.includes("Not on file"));
});
