import { test } from "node:test";
import assert from "node:assert/strict";
import {
  buildBlankDelegationPdf,
  buildDelegationPdf,
  delegationFileName,
} from "./delegationPdf";
import { blankDelegationForm } from "../data/types";

test("blank delegation PDF builds with the roster header and record mark", () => {
  const doc = buildBlankDelegationPdf();
  const blob = doc.output("blob") as Blob;
  assert.ok(blob.size > 2000, `expected a real PDF, got ${blob.size} bytes`);
  const text = doc.output() as string;
  assert.ok(text.includes("Delegation of Specified Nursing Task"), "title");
  assert.ok(text.includes("Name / title"), "roster column header");
  assert.ok(text.includes("Competency"), "roster column header");
  assert.ok(
    text.includes("Digital record generated by Complyrer"),
    "record mark",
  );
});

test("delegation roster repeats its header when it wraps across pages", () => {
  const form = blankDelegationForm();
  // A long roster forces the table onto a second page; the header must recur.
  form.roster = Array.from({ length: 40 }, (_, i) => ({
    printName: `Staff Member ${i + 1}`,
    title: "DSP",
    staffSignature: null,
    competency: ["Medication administration"],
    signatureName: `Staff Member ${i + 1}`,
    signedAt: "2026-09-10T10:00:00Z",
    rescindedDate: null,
    initials: "SM",
  }));
  const doc = buildDelegationPdf({
    agencyName: "Evergreen Care",
    individualName: "Ellis Hart",
    dmhId: "110245",
    individualLocation: "Cedar House",
    taskTitle: "Glucose monitoring",
    form,
    documentId: "delegation-test",
  });
  const pages = doc.getNumberOfPages();
  assert.ok(pages > 1, "40 roster rows paginate");
  const text = doc.output() as string;
  // The roster header ("Competency") recurs on each page the table spans (the
  // trailing accountability sections occupy the final page).
  const headerHits = (text.match(/Competency/g) ?? []).length;
  assert.ok(
    headerHits >= 2,
    `roster header should recur when it wraps (found ${headerHits})`,
  );
});

test("delegation file name is a safe download name", () => {
  assert.equal(
    delegationFileName("Glucose monitoring", "Ellis Hart"),
    "complyrer-delegation-glucose-monitoring-ellis-hart.pdf",
  );
});
