import {
  blankDelegationForm,
  DELEGATION_NON_TRANSFERABILITY_CLAUSE,
  DELEGATION_RN_RESPONSIBILITY_CLAUSE,
  type DelegationForm,
  type DelegationRosterRow,
} from "../data/types";
import { stampRecordMark, startBrandedDoc } from "./brandHeader";

const PAGE_BOTTOM = 740;

function ensureRoom(doc: ReturnType<typeof startBrandedDoc>["doc"], y: number, room: number) {
  if (y + room > PAGE_BOTTOM) {
    doc.addPage();
    return 64;
  }
  return y;
}

function heading(doc: ReturnType<typeof startBrandedDoc>["doc"], y: number, text: string, margin: number) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text(text, margin, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  return y + 16;
}

/** Format an ISO timestamp as "M/D/YY h:mm AM/PM" for signature lines. */
function formatSignatureTimestamp(iso: string): string {
  const d = new Date(iso);
  const date = d.toLocaleDateString("en-US", { month: "numeric", day: "numeric", year: "2-digit" });
  const time = d.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });
  return `${date} ${time}`;
}

function fieldLine(
  doc: ReturnType<typeof startBrandedDoc>["doc"],
  y: number,
  label: string,
  value: string,
  margin: number,
  width: number,
) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text(`${label}:`, margin, y);
  doc.setFont("helvetica", "normal");
  const shown = value || "—";
  doc.text(shown, margin, y + 12, { maxWidth: width });
  const lines = doc.splitTextToSize(shown, width);
  return y + 12 + lines.length * 11 + 6;
}

function clause(doc: ReturnType<typeof startBrandedDoc>["doc"], y: number, text: string, margin: number, width: number) {
  y = ensureRoom(doc, y, 60);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  const lines = doc.splitTextToSize(text, width);
  doc.text(lines, margin, y);
  doc.setFont("helvetica", "normal");
  return y + lines.length * 12 + 10;
}

function rosterTable(
  doc: ReturnType<typeof startBrandedDoc>["doc"],
  y: number,
  roster: DelegationRosterRow[],
  margin: number,
  width: number,
) {
  const cols = [
    { label: "Name / title", w: 130 },
    { label: "Competency", w: 130 },
    { label: "Signature", w: 110 },
    { label: "Training date", w: 70 },
    { label: "Initials", w: 40 },
  ];
  const drawHeader = () => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    let x = margin;
    for (const col of cols) {
      doc.text(col.label, x + 2, y);
      x += col.w;
    }
    doc.setFont("helvetica", "normal");
    doc.setDrawColor(160, 150, 140);
    doc.line(margin, y + 4, margin + width, y + 4);
    y += 20;
  };
  drawHeader();
  roster.forEach((row, i) => {
    // Repeat the column header when the roster wraps to a new page.
    if (y + 26 > PAGE_BOTTOM) {
      doc.addPage();
      y = 64;
      drawHeader();
    }
    let x = margin;
    const name = row.printName ? `${row.printName}${row.title ? ` — ${row.title}` : ""}` : "";
    // Signature includes timestamp (date + time) per audit requirements.
    const sigText = row.signatureName
      ? row.signedAt
        ? `${row.signatureName}\n${formatSignatureTimestamp(row.signedAt)}`
        : row.signatureName
      : "";
    const cells = [
      name,
      row.competency.length > 0 ? row.competency.join("; ") : "",
      sigText,
      row.rescindedDate || "",
      row.initials || "",
    ];
    doc.setFontSize(8);
    cells.forEach((cell, ci) => {
      doc.text(cell || "—", x + 2, y, { maxWidth: cols[ci].w - 6 });
      x += cols[ci].w;
    });
    doc.setDrawColor(210, 200, 190);
    doc.line(margin, y + 5, margin + width, y + 5);
    y += 17;
  });
  return y + 6;
}

export function buildDelegationPdf(input: {
  agencyName: string;
  individualName: string;
  dmhId: string;
  individualLocation: string;
  taskTitle: string;
  form: DelegationForm;
  /** Stable document id for the "Digital record generated by Complyrer" footer. */
  documentId?: string;
  logoDataUrl?: string | null;
}) {
  const form = input.form;
  const { doc, margin, y: startY } = startBrandedDoc(
    "Delegation of Specified Nursing Task",
    { agencyName: input.agencyName, logoDataUrl: input.logoDataUrl },
    48,
  );
  let y = startY;
  const width = 558 - margin;

  // 1. Individual
  y = heading(doc, y, "Individual", margin);
  y = fieldLine(doc, y, "Name", input.individualName, margin, width);
  y = fieldLine(doc, y, "DMH ID", input.dmhId, margin, width);
  y = fieldLine(doc, y, "Location", input.individualLocation, margin, width);

  // 2. Task and purpose
  y = heading(doc, y, "Task and purpose", margin);
  y = fieldLine(doc, y, "Task", input.taskTitle, margin, width);
  y = fieldLine(doc, y, "Purpose", form.purpose, margin, width);

  // 3. Delegation terms (Complyrer wording; same compliance meaning)
  y = heading(doc, y, "Delegation terms", margin);
  y = clause(doc, y, DELEGATION_NON_TRANSFERABILITY_CLAUSE, margin, width);
  y = clause(doc, y, DELEGATION_RN_RESPONSIBILITY_CLAUSE, margin, width);

  // 4. How to perform the task
  y = ensureRoom(doc, y, 70);
  y = heading(doc, y, "How to perform the task", margin);
  const half = width / 2 - 8;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("Steps to follow", margin, y, { maxWidth: half });
  doc.text("What to watch for, report, do — and who to contact", margin + half + 16, y, {
    maxWidth: half,
  });
  y += 14;
  doc.setDrawColor(160, 150, 140);
  doc.line(margin, y, margin + width, y);
  y += 14;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const procLines = doc.splitTextToSize(form.procedures || "—", half);
  const obsLines = doc.splitTextToSize(form.observeReportDo || "—", half);
  const block = Math.max(procLines.length, obsLines.length);
  y = ensureRoom(doc, y, block * 12);
  doc.text(procLines, margin, y);
  doc.text(obsLines, margin + half + 16, y);
  y += block * 12 + 6;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.text("* Attach any extra instruction documents", margin, y);
  doc.setFont("helvetica", "normal");
  y += 22;

  // 5. Staff authorized for this task (12 rows)
  y = ensureRoom(doc, y, 60);
  y = heading(doc, y, "Staff authorized for this task (12 rows)", margin);
  y = rosterTable(doc, y, form.roster, margin, width);

  // 6. Accountability: delegating RN + instructing professional
  y = ensureRoom(doc, y, 70);
  y = heading(doc, y, "Accountability", margin);
  y = fieldLine(doc, y, "Delegating RN (name)", form.delegatingRn.name, margin, width / 2 - 10);
  const rnSigY = y;
  y = fieldLine(doc, y, "Signature", form.delegatingRn.signatureName || "", margin, width);
  y = Math.max(y, rnSigY);
  y = fieldLine(doc, y, "Date signed", form.delegatingRn.dateSigned || "", margin, width);
  if (form.delegatingRn.contactNumber) {
    y = fieldLine(doc, y, "Contact number", form.delegatingRn.contactNumber, margin, width);
  }
  const prof = form.instructingProfessional;
  y = fieldLine(doc, y, "Instructing professional (name)", prof.name, margin, width);
  y = fieldLine(doc, y, "Signature and title", prof.title ? `${prof.name} — ${prof.title}` : prof.name, margin, width);
  y = fieldLine(doc, y, "Date", prof.signedAt || "", margin, width);
  y = fieldLine(doc, y, "Contact number", prof.contactNumber, margin, width);

  // 7. Delegation ended
  y = ensureRoom(doc, y, 50);
  y = heading(doc, y, "Delegation ended", margin);
  doc.setFontSize(9);
  const reason = form.rescindReason;
  doc.text(`${reason === "health_status_change" ? "[X]" : "[ ]"} Health status change`, margin, y);
  doc.text(`${reason === "other" ? "[X]" : "[ ]"} Other (explain below)`, margin + 220, y);
  y += 18;
  if (form.rescindExplanation) {
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(form.rescindExplanation, width);
    y = ensureRoom(doc, y, lines.length * 12);
    doc.text(lines, margin, y);
    y += lines.length * 12 + 8;
  }

  // 8. Review schedule
  y = ensureRoom(doc, y, 70);
  y = heading(doc, y, "Review schedule", margin);
  y = fieldLine(doc, y, "Review / expiry date", form.reviewDate || "Not set", margin, width);
  y = fieldLine(
    doc,
    y,
    "Inspection cadence",
    form.inspectionCadence || form.inspectionInterval,
    margin,
    width,
  );

  stampRecordMark(doc, { documentId: input.documentId, margin });
  return doc;
}

/** Build with an empty form to smoke-test layout in unit tests. */
export function buildBlankDelegationPdf() {
  return buildDelegationPdf({
    agencyName: "Test Agency",
    individualName: "Test Individual",
    dmhId: "",
    individualLocation: "",
    taskTitle: "Test task",
    form: blankDelegationForm(),
    documentId: "test-delegation",
  });
}

export function delegationFileName(taskTitle: string, individualName: string) {
  const slug = (s: string) =>
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "")
      .slice(0, 40) || "delegation";
  return `complyrer-delegation-${slug(taskTitle)}-${slug(individualName)}.pdf`;
}
