/**
 * GER (General Event Report) PDF — one report per document, Complyrer-branded,
 * stamped with the "Digital record generated by Complyrer" footer mark.
 */

import { jsPDF } from "jspdf";
import { startBrandedDoc, stampRecordMark } from "./brandHeader";
import {
  GER_EVENT_TYPE_LABELS,
  GER_SEVERITY_LABELS,
  GER_STATUS_LABELS,
  GER_NOTIFICATION_CHANNEL_LABELS,
  type GerEventType,
  type GerSeverity,
  type GerStatus,
} from "../data/ger";
import type { GerReportView } from "../data/types";

const PAGE_WIDTH = 612; // letter, pt
const MARGIN = 48;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const FOOTER_Y = 768;
const LINE_H = 11;

export interface GerPdfInput {
  report: GerReportView;
  agencyName: string;
}

export function gerReportFileName(report: GerReportView): string {
  const safeIndividual = (report.individualName || "individual")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
  const date = report.eventDate || "undated";
  return `event-report-${safeIndividual}-${date}.pdf`;
}

function label<T extends Record<string, string>>(map: T, key: string, fallback: string): string {
  return map[key as keyof T] ?? fallback;
}

export function buildGerReportPdf(input: GerPdfInput) {
  const { report, agencyName } = input;
  const { doc, y: startY } = startBrandedDoc("General Event Report", {
    agencyName,
  });
  let y = startY;

  function ensureSpace(needed: number) {
    if (y + needed > FOOTER_Y - 12) {
      doc.addPage();
      y = 52;
    }
  }

  function headerRow(): void {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(74, 64, 54);
    const status = label(GER_STATUS_LABELS, report.status, report.status);
    doc.text(
      `Status: ${status}`,
      PAGE_WIDTH - MARGIN - doc.getTextWidth(`Status: ${status}`),
      40,
    );
    doc.setTextColor(36, 30, 24);
  }

  function metaLine(): void {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(74, 64, 54);
    const when = report.eventTime
      ? `${report.eventDate} at ${report.eventTime}`
      : report.eventDate;
    const type = label(GER_EVENT_TYPE_LABELS, report.eventType as GerEventType, report.eventType);
    const severity = label(GER_SEVERITY_LABELS, report.severity as GerSeverity, report.severity);
    const lines = doc.splitTextToSize(
      `Individual: ${report.individualName}    ·    Home: ${report.siteName}    ·    Event: ${when}\n` +
        `Type: ${type}    ·    Severity: ${severity}    ·    Location: ${report.location || "—"}`,
      CONTENT_WIDTH,
    );
    ensureSpace(lines.length * LINE_H + 6);
    doc.text(lines as string[], MARGIN, y);
    y += (lines as string[]).length * LINE_H + 10;
    doc.setTextColor(36, 30, 24);
  }

  function section(title: string, body: string): void {
    const lines = doc.splitTextToSize(body || "—", CONTENT_WIDTH);
    ensureSpace(LINE_H + lines.length * LINE_H + 10);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(title, MARGIN, y);
    y += LINE_H + 2;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.text(lines as string[], MARGIN, y);
    y += (lines as string[]).length * LINE_H + 10;
  }

  headerRow();
  metaLine();

  section("What happened", report.description);
  section("Immediate actions taken / first aid", report.actionsTaken);

  const notifications = report.notificationsMade
    .map((n) => {
      const channel = label(
        GER_NOTIFICATION_CHANNEL_LABELS,
        n.channel as keyof typeof GER_NOTIFICATION_CHANNEL_LABELS,
        n.channel,
      );
      const who = n.name ? ` — ${n.name}` : "";
      const when = n.notifiedAt ? ` (${n.notifiedAt})` : "";
      return `• ${channel}${who}${when}`;
    })
    .join("\n");
  section("Notifications made", notifications);

  section("Witnesses", report.witnesses);

  if (report.status !== "draft") {
    const status = label(GER_STATUS_LABELS, report.status, report.status);
    const reviewLines = [
      `Decision: ${status}`,
      report.reviewerName ? `Reviewed by: ${report.reviewerName}` : "",
      report.reviewedAt ? `Reviewed on: ${report.reviewedAt.slice(0, 16).replace("T", " ")}` : "",
      report.reviewNote ? `Note: ${report.reviewNote}` : "",
    ].filter(Boolean);
    section("Review", reviewLines.join("\n"));
  }

  const signedOn = report.signedAt
    ? report.signedAt.slice(0, 16).replace("T", " ")
    : "";
  ensureSpace(3 * LINE_H + 12);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Reporting staff & signature", MARGIN, y);
  y += LINE_H + 2;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  const sigLines = doc.splitTextToSize(
    `Reported by: ${report.reportedByName || "—"}\nElectronic signature: ${report.signatureName || "—"}${signedOn ? ` (signed ${signedOn})` : ""}`,
    CONTENT_WIDTH,
  );
  doc.text(sigLines as string[], MARGIN, y);
  y += (sigLines as string[]).length * LINE_H + 4;

  stampRecordMark(doc, {
    documentId: report.id,
    generatedAt: new Date().toISOString(),
  });
  return doc;
}
