/**
 * Tests for the GER (General Event Report) PDF: content coverage and the
 * "Digital record generated by Complyrer" record mark.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { buildGerReportPdf, gerReportFileName } from "./gerPdf";
import type { GerReportView } from "../data/types";

function report(overrides: Partial<GerReportView> = {}): GerReportView {
  return {
    id: "ger-1",
    agencyId: "a1",
    siteId: "s1",
    individualId: "i1",
    eventDate: "2026-09-17",
    eventTime: "14:30",
    location: "Living room",
    eventType: "fall",
    severity: "high",
    description: "Individual slipped near the couch.",
    actionsTaken: "Checked for injury; applied ice.",
    notificationsMade: [{ channel: "guardian", name: "Jane Doe", notifiedAt: "2026-09-17 15:00" }],
    witnesses: "Jodie M.",
    reportedByName: "Dana Staff",
    signatureName: "Dana Staff",
    signedAt: "2026-09-17T15:05:00Z",
    status: "approved",
    reviewerId: "u-pm",
    reviewerName: "Pat Manager",
    reviewedAt: "2026-09-18T09:00:00Z",
    reviewNote: "",
    createdBy: "u-dsp",
    createdByName: "Dana Staff",
    createdAt: "2026-09-17T15:00:00Z",
    updatedAt: "2026-09-18T09:00:00Z",
    individualName: "Shawna M.",
    siteName: "2124 Brengman Drive",
    ...overrides,
  };
}

test("GER PDF contains the report content and the Complyrer record mark", () => {
  const doc = buildGerReportPdf({ report: report(), agencyName: "Test Agency" });
  const text = doc.output();
  assert.match(text, /General Event Report/);
  assert.match(text, /Shawna M\./);
  assert.match(text, /2124 Brengman Drive/);
  assert.match(text, /Fall/);
  assert.match(text, /High/);
  assert.match(text, /slipped near the couch/);
  assert.match(text, /Dana Staff/);
  assert.match(text, /Pat Manager/);
  assert.match(text, /Digital record generated by Complyrer/);
  assert.doesNotMatch(text, /undefined/);
});

test("GER PDF review section only appears once submitted", () => {
  const draft = docText(report({ status: "draft" }));
  assert.doesNotMatch(draft, /Reviewed by/);
  const submitted = docText(report({ status: "submitted", reviewerName: "Pat Manager", reviewedAt: "2026-09-18T09:00:00Z" }));
  assert.match(submitted, /Pat Manager/);
});

function docText(r: GerReportView): string {
  return buildGerReportPdf({ report: r, agencyName: "Test Agency" }).output();
}

test("GER PDF file name is safe and descriptive", () => {
  const name = gerReportFileName(report());
  assert.match(name, /^event-report-shawna-m-2026-09-17\.pdf$/);
});
