import { test } from "node:test";
import assert from "node:assert/strict";
import {
  buildWeeklyChecklistPdf,
  buildWeeklyServiceLogPdf,
  weeklyChecklistPdfName,
} from "./hmChecklistPdf";
import type { HmWeeklyChecklist } from "../data/types";

function checklist(itemCount = 6): HmWeeklyChecklist {
  return {
    id: "c1",
    agencyId: "a1",
    siteId: "s1",
    weekOf: "2026-09-13",
    assignedToUserId: "u1",
    assignedByUserId: null,
    status: "submitted",
    submittedAt: "2026-09-15T10:00:00Z",
    items: Array.from({ length: itemCount }, (_, i) => ({
      key: `i${i}`,
      prompt: `Weekly review item number ${i + 1} to confirm on the walkthrough.`,
      answer: i % 3 === 0 ? "Y" : i % 3 === 1 ? "N" : "N/A",
      note: i % 3 === 1 ? "Replaced the battery and re-tested." : "",
    })),
    serviceLogs: [],
    attestation: {
      signedBy: "Sam Rivera",
      signedAt: "2026-09-15T10:00:00Z",
      signatureMark: "SR",
    },
    createdAt: "2026-09-15T10:00:00Z",
    updatedAt: "2026-09-15T10:00:00Z",
  };
}

test("weekly checklist PDF renders answers, attestation, and the record mark", () => {
  const doc = buildWeeklyChecklistPdf({
    agencyName: "Evergreen Care",
    siteName: "Cedar House",
    weekOf: "2026-09-13",
    checklist: checklist(),
    hmName: "Sam Rivera",
  });
  const blob = doc.output("blob") as Blob;
  assert.ok(blob.size > 2000, `expected a real PDF, got ${blob.size} bytes`);
  const text = doc.output() as string;
  assert.ok(text.includes("House Manager Weekly Review"), "title");
  assert.ok(text.includes("Weekly review item number 1"), "renders items");
  assert.ok(text.includes("HM Signature"), "attestation signature line");
  assert.ok(
    text.includes("Digital record generated by Complyrer"),
    "record mark",
  );
});

test("weekly checklist PDF keeps the record mark across pages for a long list", () => {
  const doc = buildWeeklyChecklistPdf({
    agencyName: "Evergreen Care",
    siteName: "Cedar House",
    weekOf: "2026-09-13",
    checklist: checklist(40),
    hmName: "Sam Rivera",
  });
  assert.ok(doc.getNumberOfPages() > 1, "40 items paginate");
  assert.ok(doc.output().includes("Digital record generated by Complyrer"));
});

test("weekly service log PDF renders per-kind sections and the record mark", () => {
  const doc = buildWeeklyServiceLogPdf({
    agencyName: "Evergreen Care",
    siteName: "Cedar House",
    weekOf: "2026-09-13",
    checklist: checklist(),
    hmName: "Sam Rivera",
  });
  const text = doc.output() as string;
  assert.ok(text.includes("Weekly Service Log"), "title");
  assert.ok(
    text.includes("Digital record generated by Complyrer"),
    "record mark",
  );
});

test("weekly checklist file name reflects the site and week", () => {
  assert.equal(
    weeklyChecklistPdfName("Cedar House", "2026-09-13"),
    "complyrer-hm-weekly-checklist-cedar-house-2026-09-13.pdf",
  );
});
