import { test } from "node:test";
import assert from "node:assert/strict";
import {
  buildIndividualProfilePdf,
  individualProfileFileName,
} from "./individualProfilePdf";

function baseInput() {
  return {
    agencyName: "Evergreen Care",
    legalName: "Ellis James Hart",
    goesBy: "Ellis",
    dmhId: "110245",
    siteName: "Cedar House",
    dateOfBirth: "1984-03-12",
    pcspActive: 1,
    pcspCompleted: 1,
    pcspTasks: [
      { title: "Morning routine", frequency: "Daily", completed: false },
      { title: "Evening meds", frequency: "Daily", completed: true },
    ],
    diagnosis: "Intellectual disability",
    medications: [{ name: "Levetiracetam", strength: "500 mg", kind: "scheduled" }],
    agencyContacts: [{ name: "Cameron Price", role: "House Manager · Cedar House" }],
    guardians: [
      {
        name: "Dana Hart",
        relationship: "Sibling",
        phone: "573-555-0199",
        email: "",
        preferredContact: "Phone",
      },
    ],
    providers: [
      {
        id: "p1",
        name: "Dr. Maya Chen",
        role: "PCP",
        phone: "573-555-0142",
        email: "",
        address: "",
        notes: "",
      },
    ],
    generatedByName: "Cameron Price",
    generatedAt: "2026-09-16T18:00:00.000Z",
  };
}

test("issue #81: profile PDF is an agency-branded face sheet of the Overview", () => {
  const doc = buildIndividualProfilePdf(baseInput());
  const blob = doc.output("blob") as Blob;
  assert.ok(blob.size > 2000, `expected a real PDF, got ${blob.size} bytes`);
  const text = doc.output() as string;
  assert.ok(text.includes("Individual profile"), "title");
  assert.ok(text.includes("Evergreen Care"), "agency brand");
  assert.ok(text.includes("Ellis James Hart"), "legal name");
  assert.ok(text.includes("110245"), "DMH id");
  assert.ok(text.includes("Cedar House"), "site");
  assert.ok(text.includes("1 active"), "PCSP active count");
  assert.ok(text.includes("1 completed"), "PCSP completed count");
  assert.ok(text.includes("Morning routine"), "PCSP task");
  assert.ok(text.includes("Intellectual disability"), "diagnosis");
  assert.ok(text.includes("Levetiracetam"), "medication");
  assert.ok(text.includes("Cameron Price"), "agency contact");
  assert.ok(text.includes("Dana Hart"), "personal contact");
  assert.ok(text.includes("Dr. Maya Chen"), "provider");
  assert.ok(text.includes("PCP"), "provider role");
  assert.ok(
    text.includes("Digital record generated by Complyrer"),
    "record mark",
  );
  assert.ok(!text.includes("client"), "no client noun");
  assert.ok(!text.includes("patient"), "no patient noun");
});

test("issue #81: profile PDF is honest about empty sections", () => {
  const doc = buildIndividualProfilePdf({
    ...baseInput(),
    dmhId: "",
    pcspActive: 0,
    pcspCompleted: 0,
    pcspTasks: [],
    diagnosis: "",
    medications: [],
    agencyContacts: [],
    guardians: [],
    providers: [],
  });
  const text = doc.output() as string;
  assert.ok(text.includes("No PCSP tasks on this chart yet."), "empty PCSP");
  assert.ok(text.includes("No medications on this chart."), "empty meds");
  assert.ok(text.includes("No providers yet."), "empty providers");
  assert.ok(text.includes("Not on file"), "honest blanks");
});

test("issue #81: profile filename uses the Individual and date", () => {
  assert.equal(
    individualProfileFileName("Ellis Hart", "2026-09-16T18:00:00.000Z"),
    "complyrer-profile-ellis-hart-2026-09-16.pdf",
  );
});
