/**
 * individualProfilePdf.ts — issue #81 "Print profile": an agency-branded
 * Individual face sheet containing the chart Overview content.
 *
 * Distinct from "Generate consultation", which is appointment-scoped: this
 * document is the Individual's profile snapshot (identity, PCSP summary,
 * diagnoses, medications, contacts) with the agency brand header and the
 * "Digital record generated by Complyrer" mark on every page.
 */
import { jsPDF } from "jspdf";
import type { GuardianContact, ProviderContact } from "../data/planStack";
import { stampRecordMark, startBrandedDoc } from "./brandHeader";

const NOT_ON_FILE = "Not on file";
const PAGE_BOTTOM = 740;

function present(value: string | null | undefined) {
  const trimmed = (value ?? "").trim();
  return trimmed || NOT_ON_FILE;
}

function slug(value: string) {
  return value
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, "-")
    .replaceAll(/(^-|-$)/g, "");
}

export function individualProfileFileName(individualName: string, generatedAt: string) {
  const date = generatedAt.slice(0, 10);
  return `complyrer-profile-${slug(individualName) || "individual"}-${date}.pdf`;
}

export interface ProfilePdfContact {
  name: string;
  role: string;
  phone: string;
  email: string;
  address: string;
  notes: string;
}

export function buildIndividualProfilePdf(input: {
  agencyName: string;
  legalName: string;
  goesBy: string;
  dmhId: string;
  siteName: string;
  dateOfBirth: string;
  pcspActive: number;
  pcspCompleted: number;
  pcspTasks: { title: string; frequency: string; completed: boolean }[];
  diagnosis: string;
  medications: { name: string; strength: string; kind: string }[];
  agencyContacts: { name: string; role: string }[];
  guardians: GuardianContact[];
  providers: ProviderContact[];
  generatedByName: string;
  generatedAt: string;
  logoDataUrl?: string | null;
}) {
  const { doc, margin, y: startY } = startBrandedDoc("Individual profile", {
    agencyName: input.agencyName,
    logoDataUrl: input.logoDataUrl,
  });
  const contentWidth = 504;
  let y = startY;

  const ensureSpace = (needed: number) => {
    if (y + needed > PAGE_BOTTOM) {
      doc.addPage();
      y = 64;
    }
  };

  const sectionTitle = (title: string) => {
    ensureSpace(48);
    y += 8;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(47, 70, 48);
    doc.text(title, margin, y);
    y += 18;
  };

  const writePair = (label: string, value: string) => {
    ensureSpace(30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(95, 81, 69);
    doc.text(label, margin, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(36, 30, 24);
    const lines = doc.splitTextToSize(value, contentWidth);
    doc.text(lines, margin, y + 12);
    y += 12 + lines.length * 14 + 6;
  };

  const writeContact = (contact: ProfilePdfContact) => {
    ensureSpace(60);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(36, 30, 24);
    doc.text(contact.name, margin, y);
    y += 14;
    if (contact.role.trim()) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(95, 81, 69);
      doc.text(contact.role, margin, y);
      y += 14;
    }
    const details = [
      contact.phone.trim() ? `Phone: ${contact.phone.trim()}` : "",
      contact.email.trim() ? `Email: ${contact.email.trim()}` : "",
      contact.address.trim() ? `Address: ${contact.address.trim()}` : "",
      contact.notes.trim() ? `Notes: ${contact.notes.trim()}` : "",
    ].filter(Boolean);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(36, 30, 24);
    if (details.length === 0) {
      doc.text(NOT_ON_FILE, margin, y);
      y += 14;
    } else {
      for (const detail of details) {
        const lines = doc.splitTextToSize(detail, contentWidth);
        ensureSpace(lines.length * 14 + 4);
        doc.text(lines, margin, y);
        y += lines.length * 14;
      }
      y += 4;
    }
    y += 8;
  };

  // Identity strip
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(36, 30, 24);
  const nameLines = doc.splitTextToSize(input.legalName, contentWidth);
  doc.text(nameLines, margin, y);
  y += nameLines.length * 17 + 6;
  writePair("Goes by", present(input.goesBy));
  if (input.dmhId.trim()) writePair("DMH ID", input.dmhId.trim());
  writePair("Site", present(input.siteName));
  writePair("Date of birth", present(input.dateOfBirth));

  // PCSP summary
  sectionTitle("PCSP summary");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(36, 30, 24);
  ensureSpace(24);
  doc.text(`${input.pcspActive} active · ${input.pcspCompleted} completed`, margin, y);
  y += 18;
  for (const task of input.pcspTasks) {
    const label = `${task.completed ? "✓ " : "• "}${task.title}${
      task.frequency ? ` — ${task.frequency}` : ""
    }`;
    const lines = doc.splitTextToSize(label, contentWidth);
    ensureSpace(lines.length * 14 + 4);
    doc.text(lines, margin, y);
    y += lines.length * 14 + 2;
  }
  if (input.pcspTasks.length === 0) {
    ensureSpace(20);
    doc.setFont("helvetica", "italic");
    doc.text("No PCSP tasks on this chart yet.", margin, y);
    y += 18;
  }

  // Diagnoses
  sectionTitle("Diagnoses");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(36, 30, 24);
  const diagnosisLines = doc.splitTextToSize(present(input.diagnosis), contentWidth);
  ensureSpace(diagnosisLines.length * 14 + 4);
  doc.text(diagnosisLines, margin, y);
  y += diagnosisLines.length * 14 + 4;

  // Medications
  sectionTitle("Medications");
  if (input.medications.length === 0) {
    ensureSpace(20);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(11);
    doc.text("No medications on this chart.", margin, y);
    y += 18;
  } else {
    for (const med of input.medications) {
      const label = `• ${med.name}${med.strength ? ` — ${med.strength}` : ""} (${med.kind === "prn" ? "PRN" : "Scheduled"})`;
      const lines = doc.splitTextToSize(label, contentWidth);
      ensureSpace(lines.length * 14 + 4);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(36, 30, 24);
      doc.text(lines, margin, y);
      y += lines.length * 14 + 2;
    }
  }

  // Contacts
  sectionTitle("Contacts");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(95, 81, 69);
  ensureSpace(24);
  doc.text("Agency contacts", margin, y);
  y += 16;
  if (input.agencyContacts.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(36, 30, 24);
    doc.text("No agency contacts assigned yet.", margin, y);
    y += 18;
  } else {
    for (const contact of input.agencyContacts) {
      ensureSpace(32);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(36, 30, 24);
      doc.text(contact.name, margin, y);
      y += 14;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(95, 81, 69);
      doc.text(contact.role, margin, y);
      y += 18;
    }
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(95, 81, 69);
  ensureSpace(24);
  doc.text("Personal contacts", margin, y);
  y += 16;
  if (input.guardians.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(36, 30, 24);
    doc.text("No personal contacts on file.", margin, y);
    y += 18;
  } else {
    for (const guardian of input.guardians) {
      writeContact({
        name: guardian.name,
        role: guardian.relationship,
        phone: guardian.phone,
        email: guardian.email,
        address: guardian.address ?? "",
        notes: guardian.notes ?? "",
      });
    }
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(95, 81, 69);
  ensureSpace(24);
  doc.text("Providers", margin, y);
  y += 16;
  if (input.providers.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(36, 30, 24);
    doc.text("No providers yet.", margin, y);
    y += 18;
  } else {
    for (const provider of input.providers) {
      writeContact(provider);
    }
  }

  stampRecordMark(doc, {
    documentId: `profile-${slug(input.legalName) || "individual"}`,
    generatedAt: input.generatedAt,
  });
  return doc as jsPDF;
}
