/**
 * Issue #100 — Monthly MAR PDF for an Individual chart. Renders the profile
 * header, the medication configuration list, the scheduled administration
 * grid, the PRN log, the staff signature log, and flagged concerns —
 * stamped with the Complyrer record mark. Landscape letter; names are
 * never pre-printed for pen entry (initials recorded at administration
 * time carry over verbatim).
 */
import { jsPDF } from "jspdf";
import { stampRecordMark } from "./brandHeader";
import {
  marAdminStatusLabel,
  marConcernTypeLabel,
  type MarConcern,
  type MarMonthGrid,
  type MarPrnLog,
  type MedicationMarView,
} from "../data/mar";
import { monthLabel } from "../data/mileage";

export interface MarMonthlyPdfInput {
  individualName: string;
  monthKey: string;
  meds: MedicationMarView[];
  grid: MarMonthGrid;
  prnLogs: MarPrnLog[];
  signatureLog: Array<{ initials: string; name: string }>;
  concerns: MarConcern[];
  generatedByName: string;
  generatedAt: string;
}

function slug(value: string) {
  return value
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, "-")
    .replaceAll(/(^-|-$)/g, "");
}

export function marMonthlyFileName(individualName: string, monthKey: string) {
  return `complyrer-mar-${slug(individualName)}-${monthKey}.pdf`;
}

const PAGE_W = 792; // letter landscape, pt
const MARGIN = 36;
const CONTENT_W = PAGE_W - MARGIN * 2;
const FOOTER_Y = 572;

type RGB = [number, number, number];
const INK: RGB = [36, 30, 24];
const EVERGREEN: RGB = [47, 70, 48];
const HEADER_FILL: RGB = [233, 229, 221];

function monthFileLabel(monthKey: string) {
  return monthLabel(monthKey);
}

export function buildMarMonthlyPdf(input: MarMonthlyPdfInput): jsPDF {
  const doc = new jsPDF({ unit: "pt", format: "letter", orientation: "landscape" });
  let y = MARGIN + 10;

  function heading(text: string, size = 13) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(size);
    doc.setTextColor(...EVERGREEN);
    doc.text(text, MARGIN, y);
    y += size + 6;
    doc.setTextColor(...INK);
  }

  function ensureSpace(needed: number) {
    if (y + needed > FOOTER_Y - 12) {
      doc.addPage();
      y = MARGIN + 10;
    }
  }

  // Title block
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...EVERGREEN);
  doc.text("Monthly Medication Administration Record", MARGIN, y);
  y += 24;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...INK);
  doc.text(`Individual: ${input.individualName}`, MARGIN, y);
  y += 14;
  doc.text(`Month: ${monthFileLabel(input.monthKey)}`, MARGIN, y);
  y += 14;
  doc.text(
    `Generated by ${input.generatedByName} on ${input.generatedAt.slice(0, 10)}`,
    MARGIN,
    y,
  );
  y += 20;

  // Medication configuration list
  heading("Medications", 12);
  for (const med of input.meds) {
    ensureSpace(48);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    const status = med.mar.status === "active" ? "Active" : "Discontinued";
    doc.text(`${med.name} ${med.strength} (${med.kind}) — ${status}`, MARGIN, y);
    y += 13;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    const lines = doc.splitTextToSize(
      [
        med.mar.dosageForm ? `Form: ${med.mar.dosageForm}` : null,
        med.mar.indication ? `For: ${med.mar.indication}` : null,
        med.mar.instructions ? `Instructions: ${med.mar.instructions}` : null,
        med.kind === "scheduled" && med.mar.timeSlots.length > 0
          ? `Times: ${med.mar.timeSlots.join(", ")}`
          : null,
        med.mar.frequencyLabel ? `Frequency: ${med.mar.frequencyLabel}` : null,
        med.mar.scheduleRepeat ? `Repeat: ${med.mar.scheduleRepeat}` : null,
        med.mar.route ? `Route: ${med.mar.route}` : null,
        med.mar.prescriber ? `Prescriber: ${med.mar.prescriber}` : null,
        med.kind === "prn" && med.mar.prnCriteria ? `PRN criteria: ${med.mar.prnCriteria}` : null,
        med.mar.beginAt ? `Begin: ${med.mar.beginAt.slice(0, 10)}` : null,
        med.mar.discontinuedOn ? `Discontinued: ${med.mar.discontinuedOn.slice(0, 10)}` : null,
      ]
        .filter(Boolean)
        .join("  ·  ") as string,
      CONTENT_W,
    ) as string[];
    doc.text(lines, MARGIN, y);
    y += lines.length * 11 + 6;
  }

  // Scheduled grid
  heading("Scheduled administration grid", 12);
  const scheduledRows = input.grid.rows.filter((row) => row.timeSlot != null);
  if (scheduledRows.length > 0) {
    const labelW = 150;
    const dayW = (CONTENT_W - labelW) / input.grid.daysInMonth;
    const cellH = 16;
    const headerH = 14;
    ensureSpace(headerH + cellH);
    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setFillColor(...HEADER_FILL);
    doc.rect(MARGIN, y, labelW, headerH, "FD");
    doc.text("Medication / time", MARGIN + 4, y + 10);
    for (let d = 1; d <= input.grid.daysInMonth; d++) {
      const x = MARGIN + labelW + (d - 1) * dayW;
      doc.rect(x, y, dayW, headerH, "FD");
      doc.text(String(d), x + dayW / 2, y + 10, { align: "center" });
    }
    y += headerH;
    doc.setFont("helvetica", "normal");
    for (const row of scheduledRows) {
      ensureSpace(cellH);
      doc.rect(MARGIN, y, labelW, cellH, "FD");
      const wrapped = doc.splitTextToSize(
        `${row.medicationName} ${row.timeSlot}`,
        labelW - 8,
      ) as string[];
      doc.setFontSize(7);
      doc.text(wrapped.slice(0, 1), MARGIN + 4, y + 11);
      doc.setFontSize(8);
      row.cells.forEach((cell, i) => {
        const x = MARGIN + labelW + i * dayW;
        doc.rect(x, y, dayW, cellH);
        const admin = cell.administration;
        if (!admin) return;
        const cx = x + dayW / 2;
        const cy = y + 11;
        doc.text(admin.initials, cx, cy, { align: "center" });
        if (admin.status !== "given") {
          // Circled initials per DMH: circled time slot for refused/omitted/held.
          const tw = doc.getTextWidth(admin.initials);
          doc.ellipse(cx, y + cellH / 2 - 1, tw / 2 + 4, 7);
        }
      });
      y += cellH;
    }
    y += 6;
    doc.setFontSize(8);
    doc.text(
      "Circled initials = refused, omitted, or held (see reasons below where flagged).",
      MARGIN,
      y,
    );
    y += 14;
  }

  // PRN log
  heading("PRN administrations", 12);
  if (input.prnLogs.length === 0) {
    doc.setFontSize(9);
    doc.text("No PRN doses recorded this month.", MARGIN, y);
    y += 16;
  } else {
    for (const log of input.prnLogs) {
      ensureSpace(42);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      const med = input.meds.find((m) => m.id === log.medicationId);
      doc.text(
        `${log.givenAt.slice(0, 10)} — ${med?.name ?? "Medication"} ${med?.strength ?? ""} (${log.pillsGiven} pill${log.pillsGiven === 1 ? "" : "s"}) — ${log.initials}`,
        MARGIN,
        y,
      );
      y += 12;
      doc.setFont("helvetica", "normal");
      const lines = doc.splitTextToSize(
        `Reason: ${log.reasonGiven}  ·  Effectiveness: ${log.effectiveness}`,
        CONTENT_W,
      ) as string[];
      doc.setFontSize(8.5);
      doc.text(lines, MARGIN, y);
      y += lines.length * 11 + 8;
    }
  }

  // Signature log
  heading("Staff signature log", 12);
  if (input.signatureLog.length === 0) {
    doc.setFontSize(9);
    doc.text("No administrations recorded this month.", MARGIN, y);
    y += 16;
  } else {
    for (const entry of input.signatureLog) {
      ensureSpace(16);
      doc.setFontSize(9);
      doc.text(`${entry.initials} — ${entry.name || ""}`, MARGIN, y);
      y += 14;
    }
  }

  // Concerns
  heading("Flagged concerns", 12);
  if (input.concerns.length === 0) {
    doc.setFontSize(9);
    doc.text("No concerns flagged this month.", MARGIN, y);
    y += 16;
  } else {
    for (const concern of input.concerns) {
      ensureSpace(42);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      const med = input.meds.find((m) => m.id === concern.medicationId);
      doc.text(
        `${marConcernTypeLabel(concern.concernType)} — ${med?.name ?? "Medication"} — flagged ${concern.createdAt.slice(0, 10)} by ${concern.initials}`,
        MARGIN,
        y,
      );
      y += 12;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      const lines = doc.splitTextToSize(concern.description, CONTENT_W) as string[];
      doc.text(lines, MARGIN, y);
      y += lines.length * 11;
      if (concern.resolvedAt) {
        doc.text(`Resolved ${concern.resolvedAt.slice(0, 10)}.`, MARGIN, y);
        y += 12;
      }
      y += 4;
    }
  }

  // Non-given reasons (the paper legend for circled initials)
  const flagged = input.grid.rows
    .flatMap((row) => row.cells.map((cell) => cell.administration))
    .filter((admin) => admin != null && admin.status !== "given");
  if (flagged.length > 0) {
    heading("Refused / omitted / held reasons", 12);
    for (const admin of flagged) {
      ensureSpace(24);
      doc.setFontSize(8.5);
      const med = input.meds.find((m) => m.id === admin!.medicationId);
      const lines = doc.splitTextToSize(
        `${admin!.administeredOn} ${admin!.timeSlot} — ${med?.name ?? "Medication"}: ${marAdminStatusLabel(admin!.status)} — ${admin!.reason} (${admin!.initials})${admin!.notifyNurse ? " — nurse notified" : ""}`,
        CONTENT_W,
      ) as string[];
      doc.text(lines, MARGIN, y);
      y += lines.length * 11 + 4;
    }
  }

  stampRecordMark(doc, {
    documentId: `mar-${slug(input.individualName)}-${input.monthKey}`,
    margin: MARGIN,
    footerY: FOOTER_Y,
  });
  return doc;
}
