/**
 * Issue #100 — MAR monthly PDF: profile, medication configuration list,
 * scheduled grid with circled initials, PRN log, signature log, concerns,
 * and the Complyrer record mark.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { buildMarMonthlyPdf, marMonthlyFileName } from "./marMonthlyPdf";
import {
  marGridForMonth,
  type MarAdministration,
  type MarConcern,
  type MarPrnLog,
  type MedicationMarView,
} from "../data/mar";

function med(overrides: Partial<MedicationMarView> = {}): MedicationMarView {
  return {
    id: "m1",
    agencyId: "a1",
    individualId: "i1",
    name: "Lisinopril",
    strength: "10 mg",
    kind: "scheduled",
    controlled: false,
    pillsPerDay: 1,
    remainingPills: 30,
    lastDeliveryOn: null,
    lastCountdownOn: null,
    mar: {
      dosageForm: "tablet",
      indication: "blood pressure",
      instructions: "take with water",
      beginAt: "2026-09-01",
      frequencyLabel: "once daily",
      scheduleRepeat: "every day",
      timeSlots: ["08:00"],
      route: "by mouth",
      prescriber: "Dr. Patel",
      prnCriteria: "",
      status: "active",
      discontinuedOn: null,
      orderAttachment: null,
    },
    ...overrides,
  };
}

function administration(overrides: Partial<MarAdministration> = {}): MarAdministration {
  return {
    id: "ad1",
    agencyId: "a1",
    individualId: "i1",
    medicationId: "m1",
    administeredOn: "2026-09-02",
    timeSlot: "08:00",
    status: "given",
    initials: "AB",
    administeredByName: "Ava Brooks",
    administeredByUserId: "u1",
    reason: "",
    notifyNurse: false,
    createdAt: "2026-09-02T08:05:00Z",
    pillsGiven: 1,
    ...overrides,
  };
}

test("MAR monthly PDF names the file per individual and month", () => {
  assert.equal(marMonthlyFileName("Jamie Rivera", "2026-09"), "complyrer-mar-jamie-rivera-2026-09.pdf");
});

test("MAR monthly PDF renders the medication config, grid initials, PRN log, signatures, and the record mark", () => {
  const meds = [med()];
  const administrations = [administration()];
  const prnLogs: MarPrnLog[] = [
    {
      id: "p1",
      agencyId: "a1",
      individualId: "i1",
      medicationId: "m1",
      givenAt: "2026-09-05T21:00:00Z",
      pillsGiven: 1,
      reasonGiven: "headache 6/10",
      effectiveness: "helped within an hour",
      initials: "CD",
      administeredByName: "Casey Diaz",
      createdAt: "2026-09-05T21:05:00Z",
    },
  ];
  const grid = marGridForMonth({ meds, administrations, prnLogs, monthKey: "2026-09" });
  const concerns: MarConcern[] = [
    {
      id: "c1",
      agencyId: "a1",
      individualId: "i1",
      medicationId: "m1",
      administrationId: null,
      prnLogId: null,
      concernType: "adverse_reaction",
      description: "Rash on arm noted after evening dose.",
      initials: "AB",
      flaggedByName: "Ava Brooks",
      nurseNotified: true,
      createdAt: "2026-09-06T09:00:00Z",
      resolvedAt: null,
    },
  ];
  const doc = buildMarMonthlyPdf({
    individualName: "Jamie Rivera",
    monthKey: "2026-09",
    meds,
    grid,
    prnLogs,
    signatureLog: [
      { initials: "AB", name: "Ava Brooks" },
      { initials: "CD", name: "Casey Diaz" },
    ],
    concerns,
    generatedByName: "Ava Brooks",
    generatedAt: "2026-09-18T10:00:00Z",
  });
  const text = doc.output();
  assert.ok(text.includes("Monthly Medication Administration Record"), "has the title");
  assert.ok(text.includes("Jamie Rivera"), "names the individual");
  assert.ok(text.includes("Lisinopril"), "lists the medication");
  assert.ok(text.includes("10 mg"), "shows the strength");
  assert.ok(text.includes("Dr. Patel"), "shows the prescriber");
  assert.ok(text.includes("AB"), "prints scheduled initials");
  assert.ok(text.includes("headache 6/10"), "prints the PRN log");
  assert.ok(text.includes("Casey Diaz"), "prints the signature log");
  assert.ok(text.includes("Adverse reaction"), "prints the flagged concern");
  assert.ok(text.includes("Digital record generated by Complyrer"), "carries the record mark");
});

test("MAR monthly PDF includes the refused-dose reasons legend", () => {
  const meds = [med()];
  const administrations = [
    administration({
      id: "ad2",
      status: "refused",
      initials: "CD",
      reason: "individual declined dose",
      notifyNurse: true,
      administeredOn: "2026-09-03",
    }),
  ];
  const grid = marGridForMonth({ meds, administrations, prnLogs: [], monthKey: "2026-09" });
  const doc = buildMarMonthlyPdf({
    individualName: "Jamie Rivera",
    monthKey: "2026-09",
    meds,
    grid,
    prnLogs: [],
    signatureLog: [{ initials: "CD", name: "Casey Diaz" }],
    concerns: [],
    generatedByName: "Casey Diaz",
    generatedAt: "2026-09-18T10:00:00Z",
  });
  const text = doc.output();
  assert.ok(text.includes("individual declined dose"), "prints the refused reason");
  assert.ok(text.includes("Refused / omitted / held reasons"), "prints the legend heading");
});
