import { test } from "node:test";
import assert from "node:assert/strict";
import {
  buildMileageMonthPdf,
  buildMileageYearPdf,
  mileageMonthFileName,
  mileageYearFileName,
} from "./mileagePdf";
import type { MileageTripView } from "../data/types";

const PEOPLE = [
  { id: "p1", name: "Jamie Rivera" },
  { id: "p2", name: "Casey Lee" },
  { id: "p3", name: "Morgan Diaz" },
];

function trip(overrides: Partial<MileageTripView> = {}): MileageTripView {
  return {
    id: "t1",
    agencyId: "a1",
    siteId: "s1",
    tripDate: "2026-09-03",
    odometerStart: 1000,
    odometerEnd: 1040,
    miles: 40,
    riderIds: ["p1", "p2"],
    reason: "Doctor appointment",
    backfilled: false,
    driverName: "Dana Staff",
    signatureName: "Dana Staff",
    createdBy: "u1",
    createdAt: "2026-09-03T10:00:00Z",
    riderShares: [
      { individualId: "p1", miles: 20 },
      { individualId: "p2", miles: 20 },
    ],
    ...overrides,
  };
}

test("mileage month PDF produces a non-empty downloadable blob", async () => {
  const doc = buildMileageMonthPdf({
    agencyName: "Evergreen Care",
    siteName: "Maple House",
    monthKey: "2026-09",
    people: PEOPLE,
    trips: [
      trip(),
      trip({
        id: "t2",
        tripDate: "2026-09-10",
        odometerStart: 1040,
        odometerEnd: 1070,
        miles: 30,
        riderIds: ["p1", "p2", "p3"],
        riderShares: [
          { individualId: "p1", miles: 10 },
          { individualId: "p2", miles: 10 },
          { individualId: "p3", miles: 10 },
        ],
      }),
    ],
    totalMiles: 70,
    milesByIndividualId: { p1: 30, p2: 30, p3: 10 },
  });
  const blob = doc.output("blob") as Blob;
  assert.ok(blob.size > 2000, `expected a real PDF, got ${blob.size} bytes`);
  assert.match(doc.output("datauristring"), /application\/pdf/);
  assert.ok(
    doc.output().includes("Digital record generated by Complyrer"),
    "every generated document must carry the Complyrer record mark",
  );
});

test("mileage month PDF works with no trips and no people", async () => {
  const doc = buildMileageMonthPdf({
    agencyName: "Evergreen Care",
    siteName: "Maple House",
    monthKey: "2026-09",
    people: [],
    trips: [],
    totalMiles: 0,
    milesByIndividualId: {},
  });
  const blob = doc.output("blob") as Blob;
  assert.ok(blob.size > 1000, `expected a real PDF, got ${blob.size} bytes`);
});

test("mileage month PDF spans multiple pages for many trips", () => {
  const trips: MileageTripView[] = Array.from({ length: 60 }, (_, i) =>
    trip({
      id: `t${i}`,
      tripDate: `2026-09-${String((i % 28) + 1).padStart(2, "0")}`,
      odometerStart: 1000 + i * 40,
      odometerEnd: 1040 + i * 40,
    }),
  );
  const doc = buildMileageMonthPdf({
    agencyName: "Evergreen Care",
    siteName: "Maple House",
    monthKey: "2026-09",
    people: PEOPLE,
    trips,
    totalMiles: 2400,
    milesByIndividualId: { p1: 1200, p2: 1200, p3: 0 },
  });
  assert.ok(doc.getNumberOfPages() > 1, "expected pagination for 60 trips");
  assert.ok(
    doc.output().includes("Digital record generated by Complyrer"),
    "record mark must survive pagination",
  );
});

test("mileage month file name is a safe download name", () => {
  assert.equal(
    mileageMonthFileName("Maple House", "2026-09"),
    "complyrer-mileage-log-maple-house-2026-09.pdf",
  );
});

test("mileage month PDF sign-off uses role labels, never pre-printed individual names", () => {
  const doc = buildMileageMonthPdf({
    agencyName: "Evergreen Care",
    siteName: "Maple House",
    monthKey: "2026-09",
    people: PEOPLE,
    trips: [trip()],
    totalMiles: 40,
    milesByIndividualId: { p1: 20, p2: 20 },
  });
  const text = doc.output() as string;
  assert.ok(text.includes("Driver print name:"), "driver print-name line");
  assert.ok(text.includes("Driver signature:"), "driver signature line");
  assert.ok(
    text.includes("House manager print name:"),
    "house manager print-name line",
  );
  assert.ok(
    text.includes("House manager signature:"),
    "house manager signature line",
  );
  assert.ok(
    !text.includes("Sign name:"),
    "old per-person sign-off label must be gone",
  );
  // Individuals appear only as rider/mileage columns, never as sign-off rows:
  // the old layout printed one "Print name:" line per individual.
  const printNameCount = (text.match(/Print name:/g) ?? []).length;
  assert.ok(
    printNameCount <= 2,
    `expected at most the two role print-name lines, found ${printNameCount}`,
  );
});

test("mileage yearly PDF renders Jan–Dec columns, yearly totals, and the grand total", async () => {
  const doc = buildMileageYearPdf({
    agencyName: "Evergreen Care",
    siteName: "Maple House",
    year: 2026,
    people: PEOPLE,
    summary: {
      year: 2026,
      rows: [
        { individualId: "p1", months: [20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], yearlyTotal: 20 },
        { individualId: "p2", months: [10, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], yearlyTotal: 25 },
        { individualId: "p3", months: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], yearlyTotal: 0 },
      ],
      grandTotal: { months: [30, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], yearlyTotal: 45 },
    },
  });
  const blob = doc.output("blob") as Blob;
  assert.ok(blob.size > 2000, `expected a real PDF, got ${blob.size} bytes`);
  const text = doc.output();
  assert.ok(text.includes("Yearly Mileage Tracking"), "title");
  assert.ok(text.includes("Grand Total"), "grand total row");
  assert.ok(
    text.includes("Digital record generated by Complyrer"),
    "every generated document must carry the Complyrer record mark",
  );
  assert.ok(
    mileageYearFileName("Maple House", 2026).endsWith("-2026.pdf"),
    "yearly filename carries the year",
  );
});

test("mileage yearly PDF agency-wide mode draws one site group header per site", () => {
  const doc = buildMileageYearPdf({
    agencyName: "Evergreen Care",
    siteName: "All sites",
    year: 2026,
    people: [
      { id: "p1", name: "Jamie Rivera" },
      { id: "p2", name: "Casey Lee" },
      { id: "p3", name: "Morgan Diaz" },
    ],
    summary: {
      year: 2026,
      rows: [
        { individualId: "p1", months: [20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], yearlyTotal: 20 },
        { individualId: "p2", months: [10, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], yearlyTotal: 25 },
        { individualId: "p3", months: [5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], yearlyTotal: 5 },
      ],
      grandTotal: { months: [35, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], yearlyTotal: 50 },
    },
    siteNameByIndividualId: {
      p1: "Maple House",
      p2: "Maple House",
      p3: "Oakwood House",
    },
  });
  const text = doc.output() as string;
  assert.ok(text.includes("All sites"), "agency-wide header names the scope");
  assert.ok(text.includes("Maple House"), "first site group header");
  assert.ok(text.includes("Oakwood House"), "second site group header");
  assert.ok(text.includes("Grand Total"), "grand total row");
  assert.ok(
    text.includes("Digital record generated by Complyrer"),
    "every generated document must carry the Complyrer record mark",
  );
  const blob = doc.output("blob") as Blob;
  assert.ok(blob.size > 2000, `expected a real PDF, got ${blob.size} bytes`);
});
