import { test } from "node:test";
import assert from "node:assert/strict";
import {
  buildDrillsMonthPdf,
  buildEquipmentMonthPdf,
  buildSafetyMonthPdf,
  drillsFileName,
  equipmentFileName,
  safetyFileName,
} from "./monthlyChecksPdf";
import { SAFETY_LINE_DEFS } from "../data/monthlyChecks";
import type {
  AdaptiveEquipment,
  EmergencyDrill,
  EquipmentMonthLog,
  HomeSafetyReport,
} from "../data/monthlyChecks";

const FORBIDDEN = ["client", "patient", "t-log"];
function assertIndividualSafe(text: string, label: string) {
  const lower = text.toLowerCase();
  for (const word of FORBIDDEN) {
    assert.ok(!lower.includes(word), `${label} contains forbidden wording "${word}"`);
  }
}

function equipmentItem(
  i: number,
  log?: Partial<EquipmentMonthLog>,
): AdaptiveEquipment & { log?: EquipmentMonthLog } {
  return {
    id: `eq-${i}`,
    agencyId: "a1",
    individualId: "ind-1",
    name: `Adaptive item ${i}`,
    source: "manual",
    active: true,
    log: log
      ? {
          id: `log-${i}`,
          equipmentId: `eq-${i}`,
          monthKey: "2026-09",
          checkedOn: "2026-09-05",
          initials: "TS",
          checkedByUserId: "u1",
          comments: "",
          ...log,
        }
      : undefined,
  };
}

test("adaptive equipment PDF stamps the record mark and stays individuals-safe", () => {
  const doc = buildEquipmentMonthPdf({
    agencyName: "Evergreen Care",
    individualName: "Ellis Hart",
    dmhId: "110245",
    monthKey: "2026-09",
    items: [equipmentItem(1, {}), equipmentItem(2)],
  });
  const blob = doc.output("blob") as Blob;
  assert.ok(blob.size > 1500, `expected a real PDF, got ${blob.size} bytes`);
  const text = doc.output() as string;
  assert.ok(text.includes("Adaptive Equipment Log"), "title");
  assert.ok(text.includes("Ellis Hart"), "individual");
  assert.ok(
    text.includes("Digital record generated by Complyrer"),
    "record mark",
  );
  assertIndividualSafe(text, "equipment pdf");
});

test("adaptive equipment PDF paginates a long list and keeps the record mark on every page", () => {
  const items = Array.from({ length: 40 }, (_, i) => equipmentItem(i));
  const doc = buildEquipmentMonthPdf({
    agencyName: "Evergreen Care",
    individualName: "Ellis Hart",
    dmhId: "110245",
    monthKey: "2026-09",
    items,
  });
  assert.ok(doc.getNumberOfPages() > 1, "40 items paginate");
  assert.ok(doc.output().includes("Digital record generated by Complyrer"));
});

test("emergency drills PDF renders a monthly-review sign-off", () => {
  const drills: EmergencyDrill[] = [
    {
      id: "d1",
      agencyId: "a1",
      siteId: "s1",
      monthKey: "2026-09",
      drillType: "fire",
      date: "2026-09-05",
      time: "10:00 AM",
      evacTime: "3 minutes",
      leaderName: "Dana Staff",
      participants: "Team A",
      awakeOrSleep: "awake",
    },
  ];
  const doc = buildDrillsMonthPdf({
    agencyName: "Evergreen Care",
    siteName: "Cedar House",
    monthKey: "2026-09",
    drills,
  });
  const text = doc.output() as string;
  assert.ok(text.includes("Emergency Drills"), "title");
  assert.ok(text.includes("Monthly review"), "completion sign-off section");
  assert.ok(text.includes("Reviewed by"), "reviewer signature label");
  assert.ok(text.includes("Digital record generated by Complyrer"), "record mark");
  assertIndividualSafe(text, "drills pdf");
});

test("home safety PDF renders every safety line and a monthly-review sign-off", () => {
  const report: HomeSafetyReport = {
    id: "r1",
    agencyId: "a1",
    siteId: "s1",
    monthKey: "2026-09",
    lines: SAFETY_LINE_DEFS.map((def) => ({
      key: def.key,
      dateChecked: "2026-09-03",
      location: "Hallway",
      temp: "115",
      extra: "OK",
      checkedBy: "Dana Staff",
      signature: null,
    })),
  };
  const doc = buildSafetyMonthPdf({
    agencyName: "Evergreen Care",
    siteName: "Cedar House",
    monthKey: "2026-09",
    report,
  });
  const text = doc.output() as string;
  assert.ok(text.includes("Monthly Home Safety Report"), "title");
  assert.ok(text.includes("Smoke detector 1"), "first safety line");
  assert.ok(text.includes("Monthly review"), "completion sign-off section");
  assert.ok(text.includes("Checked by"), "per-line checked-by field");
  assert.ok(text.includes("Digital record generated by Complyrer"), "record mark");
  assertIndividualSafe(text, "safety pdf");
});

test("monthly-checks file names are safe download names", () => {
  assert.equal(
    equipmentFileName("Ellis Hart", "2026-09"),
    "complyrer-adaptive-equipment-ellis-hart-2026-09.pdf",
  );
  assert.equal(
    drillsFileName("Cedar House", "2026-09"),
    "complyrer-emergency-drills-cedar-house-2026-09.pdf",
  );
  assert.equal(
    safetyFileName("Cedar House", "2026-09"),
    "complyrer-home-safety-cedar-house-2026-09.pdf",
  );
});
