import { test } from "node:test";
import assert from "node:assert/strict";
import {
  buildPreSurveyPdf,
  buildSiteReviewPdf,
  preSurveyFileName,
  siteReviewFileName,
} from "./siteReviewPdf";
import {
  DEFAULT_SITE_FACTS,
  SITE_REVIEW_LINE_DEFS,
  type PreSurveyRow,
  type SiteReview,
} from "../data/siteReview";

function review(): SiteReview {
  return {
    id: "sr-1",
    agencyId: "a1",
    siteId: "s1",
    reviewerName: "Casey Reviewer",
    supportCoordinator: "Sam Coordinator",
    reviewedOn: "2026-09-14",
    providerOwnedControlled: true,
    heightenedScrutiny: false,
    meetsIndividualNeeds: true,
    part2Verified: true,
    lines: SITE_REVIEW_LINE_DEFS.map((def, i) => ({
      id: def.id,
      status: i % 2 === 0 ? "satisfactory" : "unsatisfactory",
      comment: i % 3 === 0 ? "Follow up on this at the next visit." : "",
    })),
    updatedAt: "2026-09-14T10:00:00Z",
  };
}

test("site review PDF renders sections and a reviewer sign-off", () => {
  const doc = buildSiteReviewPdf({
    agencyName: "Evergreen Care",
    siteName: "Cedar House",
    address: "418 Cedar Court",
    facts: { ...DEFAULT_SITE_FACTS, city: "Columbia", zip: "65202" },
    residents: ["Ellis Hart", "Jamie Rivera"],
    review: review(),
    monthlySafetyOnFile: true,
    stateCode: "MO",
  });
  const blob = doc.output("blob") as Blob;
  assert.ok(blob.size > 2000, `expected a real PDF, got ${blob.size} bytes`);
  const text = doc.output() as string;
  assert.ok(text.includes("Environmental site review"), "title");
  assert.ok(text.includes("Casey Reviewer"), "reviewer name");
  assert.ok(text.includes("Reviewer sign-off"), "completion section");
  assert.ok(text.includes("Reviewer signature"), "signature line label");
  assert.ok(
    text.includes("Digital record generated by Complyrer"),
    "record mark",
  );
});

test("pre-survey PDF keeps each individual block together and stamps the record mark", () => {
  const rows: PreSurveyRow[] = Array.from({ length: 6 }, (_, i) => ({
    name: `Individual ${i + 1}`,
    age: "42",
    sex: "F",
    medicaid: "Yes",
    diet: "No concentrated sweets",
    equipment: "Wheelchair",
    specializedMedical: "Seizure protocol",
    behaviorSupports: "BSP on file",
    dailyActivities: "Day program",
    visitHours: "9a-3p",
  }));
  const doc = buildPreSurveyPdf({
    agencyName: "Evergreen Care",
    siteName: "Cedar House",
    address: "418 Cedar Court",
    facts: { ...DEFAULT_SITE_FACTS, city: "Columbia", zip: "65202" },
    rows,
    stateCode: "MO",
  });
  const text = doc.output() as string;
  assert.ok(text.includes("Pre-survey individual information"), "title");
  assert.ok(text.includes("Individual 1"), "first individual");
  assert.ok(text.includes("Individual 6"), "last individual");
  assert.ok(
    text.includes("Digital record generated by Complyrer"),
    "record mark",
  );
});

test("site review file names are safe download names", () => {
  assert.equal(siteReviewFileName("Cedar House"), "complyrer-site-review-cedar-house.pdf");
  assert.equal(preSurveyFileName("Cedar House"), "complyrer-pre-survey-cedar-house.pdf");
});
