import { test } from "node:test";
import assert from "node:assert/strict";
import {
  buildStaffTrainingChecklistPdf,
  staffTrainingFileName,
} from "./trainingChecklistPdf";

test("staff training checklist PDF shows actual initials, never the word 'initialed'", () => {
  const doc = buildStaffTrainingChecklistPdf({
    agencyName: "Evergreen Care",
    staffName: "Jordan Ellis",
    siteNames: ["Maple House"],
    hoursTotal: 22,
    hoursWithHm: 9,
    lines: [
      {
        title: "Fire safety and evacuation routes",
        section: "Section 1",
        initials: "JE",
        signedOn: "2026-09-10",
        na: false,
        naReason: null,
        trainerName: "Sam Rivera",
      },
      {
        title: "G-tube feeding",
        section: "Section 1",
        initials: null,
        signedOn: null,
        na: true,
        naReason: "No G-tube at this home",
        trainerName: "",
      },
      {
        title: "Medication administration",
        section: "Section 2",
        initials: null,
        signedOn: null,
        na: false,
        naReason: null,
        trainerName: "",
      },
    ],
    signatures: [
      {
        siteName: "Maple House",
        staff: { name: "Jordan Ellis", signedAt: "2026-09-12T14:30:00Z" },
        hm: { name: "Sam Rivera", signedAt: "2026-09-13T09:15:00Z" },
      },
    ],
  });
  const blob = doc.output("blob") as Blob;
  assert.ok(blob.size > 2000, `expected a real PDF, got ${blob.size} bytes`);
  const text = doc.output();
  // Actual initials appear…
  assert.ok(text.includes("JE"), "actual staff initials appear on the line");
  // …and the word "initialed" never does.
  assert.ok(
    !/initialed/i.test(text),
    "the word 'initialed' must never appear — only real initials",
  );
  assert.ok(text.includes("N/A"), "N/A lines are marked");
  assert.ok(text.includes("Pending"), "unsigned lines say Pending");
  assert.ok(text.includes("Sam Rivera"), "trainer name appears");
  assert.ok(text.includes("Jordan Ellis"), "staff signature name appears");
  assert.ok(
    text.includes("Digital record generated by Complyrer"),
    "every generated document must carry the Complyrer record mark",
  );
});

test("staffTrainingFileName slugs the staff name", () => {
  assert.equal(
    staffTrainingFileName("Jordan Ellis"),
    "complyrer-training-checklist-jordan-ellis.pdf",
  );
});
