import { test } from "node:test";
import assert from "node:assert/strict";
import {
  buildStaffTrainingChecklistPdf,
  staffTrainingFileName,
} from "./trainingChecklistPdf";

test("staff training checklist PDF shows actual initials, never the word 'initialed'", () => {
  const doc = buildStaffTrainingChecklistPdf({
    agencyName: "Evergreen Care",
    staffName: "Jordan Ellis",
    siteNames: ["Cedar House"],
    hoursTotal: 22,
    hoursWithHm: 9,
    lines: [
      {
        title: "Fire safety and evacuation routes",
        section: "Section 1",
        initials: "JE",
        signedOn: "2026-09-10",
        na: false,
        naReason: null,
        trainerName: "Sam Rivera",
      },
      {
        title: "G-tube feeding",
        section: "Section 1",
        initials: null,
        signedOn: null,
        na: true,
        naReason: "No G-tube at this home",
        trainerName: "",
      },
      {
        title: "Medication administration",
        section: "Section 2",
        initials: null,
        signedOn: null,
        na: false,
        naReason: null,
        trainerName: "",
      },
    ],
    signatures: [
      {
        siteName: "Cedar House",
        staff: { name: "Jordan Ellis", signedAt: "2026-09-12T14:30:00Z" },
        hm: { name: "Sam Rivera", signedAt: "2026-09-13T09:15:00Z" },
      },
    ],
  });
  const blob = doc.output("blob") as Blob;
  assert.ok(blob.size > 2000, `expected a real PDF, got ${blob.size} bytes`);
  const text = doc.output();
  // Actual initials appear…
  assert.ok(text.includes("JE"), "actual staff initials appear on the line");
  // …and the word "initialed" never does.
  assert.ok(
    !/initialed/i.test(text),
    "the word 'initialed' must never appear — only real initials",
  );
  assert.ok(text.includes("N/A"), "N/A lines are marked");
  assert.ok(text.includes("Pending"), "unsigned lines say Pending");
  assert.ok(text.includes("Sam Rivera"), "trainer name appears");
  assert.ok(text.includes("Jordan Ellis"), "staff signature name appears");
  assert.ok(
    text.includes("Digital record generated by Complyrer"),
    "every generated document must carry the Complyrer record mark",
  );
});

test("staff training checklist repeats column headers across pages", () => {
  // 90 lines across three sections force pagination; the "Training item" /
  // "Initials / date" column header must recur so continuation pages stay
  // labeled rather than becoming a bare list.
  const lines = Array.from({ length: 90 }, (_, i) => ({
    title: `Training topic number ${i + 1}`,
    section: `Section ${Math.floor(i / 30) + 1}`,
    initials: i % 2 === 0 ? "JE" : null,
    signedOn: i % 2 === 0 ? "2026-09-10" : null,
    na: false,
    naReason: null,
    trainerName: "Sam Rivera",
  }));
  const doc = buildStaffTrainingChecklistPdf({
    agencyName: "Evergreen Care",
    staffName: "Jordan Ellis",
    siteNames: ["Cedar House"],
    hoursTotal: 40,
    hoursWithHm: 12,
    lines,
    signatures: [
      {
        siteName: "Cedar House",
        staff: { name: "Jordan Ellis", signedAt: "2026-09-12T14:30:00Z" },
        hm: { name: "Sam Rivera", signedAt: "2026-09-13T09:15:00Z" },
      },
    ],
  });
  const pages = doc.getNumberOfPages();
  assert.ok(pages > 1, "90 lines paginate");
  const text = doc.output() as string;
  const headerHits = (text.match(/Training item/g) ?? []).length;
  assert.ok(
    headerHits >= pages,
    `column header should recur per page (found ${headerHits} for ${pages} pages)`,
  );
  assert.ok(
    text.includes("Digital record generated by Complyrer"),
    "record mark survives pagination",
  );
});

test("staffTrainingFileName slugs the staff name", () => {
  assert.equal(
    staffTrainingFileName("Jordan Ellis"),
    "complyrer-training-checklist-jordan-ellis.pdf",
  );
});
