/**
 * Discreet provenance line rendered on every generated/signed document screen
 * view and stamped into every PDF footer: "Digital record generated by
 * Complyrer", optionally with the document id and generation timestamp. The
 * agency tenant name may appear alongside it (it's their instance) — the form
 * design stays Complyrer's own.
 */
export default function ComplyrerRecordMark({
  documentId,
  generatedAt,
}: {
  /** Stable id of the generated/signed document, when available. */
  documentId?: string;
  /** ISO timestamp of generation/signing, when available. */
  generatedAt?: string | null;
}) {
  const parts = ["Digital record generated by Complyrer"];
  if (documentId) parts.push(documentId);
  if (generatedAt) {
    const d = new Date(generatedAt);
    if (!Number.isNaN(d.getTime())) {
      parts.push(
        d.toLocaleString("en-US", {
          month: "short",
          day: "numeric",
          year: "numeric",
        }),
      );
    }
  }
  return <p className="record-mark">{parts.join(" · ")}</p>;
}
