/**
 * Delegation template library — domain layer.
 *
 * Workflow:
 *  1. Common templates are available across the agency.
 *  2. A DPM activates a template for a program site ("In preparation").
 *  3. A DPM or RN assigns it to an individual → an editable training draft
 *     is instantiated for that person.
 *  4. A DPM or RN reviews, edits, and approves the draft → published.
 *  5. Published material becomes visible to assigned site staff, who review
 *     and electronically sign it.
 *  6. HM/DPM views show signed, outstanding, and overdue staff.
 *
 * All template content is Complyrer-original generic starting material. It is
 * NOT a medical directive and must be individualized by the DPM/RN for the
 * person before approval. Every generated or signed document carries the
 * digital-record mark.
 */

/** The exact mark every generated or signed delegation document carries. */
export const DIGITAL_RECORD_MARK = "Digital record generated by Complyrer.";

/** Days after publication a staff acknowledgment becomes overdue. */
export const DELEGATION_ACK_DUE_DAYS = 7;

export type DelegationTemplateCategory =
  | "Health monitoring"
  | "Nutrition"
  | "Safety"
  | "Daily living support";

export interface TemplateSections {
  purpose: string;
  steps: string[];
  safetyWarnings: string[];
  documentation: string[];
}

export interface DelegationTemplate {
  id: string;
  /** Null agencyId = common template available to every agency. */
  agencyId: string | null;
  name: string;
  category: DelegationTemplateCategory;
  sections: TemplateSections;
  /** Why the DPM/RN must individualize this before approval. */
  individualizationNote: string;
  active: boolean;
}

export type DelegationActivationStatus = "active" | "deactivated";

export interface SiteDelegationActivation {
  id: string;
  agencyId: string;
  templateId: string;
  templateName: string;
  templateCategory: DelegationTemplateCategory;
  siteId: string;
  siteName: string;
  status: DelegationActivationStatus;
  activatedAt: string;
  activatedBy: string;
}

export type DelegationAssignmentStatus = "assigned" | "ended";

export interface IndividualDelegationAssignment {
  id: string;
  agencyId: string;
  activationId: string;
  templateId: string;
  templateName: string;
  individualId: string;
  individualName: string;
  siteId: string;
  siteName: string;
  status: DelegationAssignmentStatus;
  assignedAt: string;
  assignedBy: string;
}

export type TrainingMaterialStatus = "draft" | "in_review" | "published";

export interface TrainingMaterialContent {
  templateId: string;
  templateName: string;
  individualId: string;
  individualName: string;
  siteId: string;
  siteName: string;
  purpose: string;
  steps: string[];
  safetyWarnings: string[];
  documentation: string[];
  /** DPM/RN person-specific additions, edited during review. */
  individualNotes: string;
  individualizationNote: string;
  generatedMark: string;
}

export interface DelegationTrainingMaterial {
  id: string;
  agencyId: string;
  assignmentId: string;
  status: TrainingMaterialStatus;
  draftContent: TrainingMaterialContent;
  publishedContent: TrainingMaterialContent | null;
  submittedAt: string | null;
  approvedAt: string | null;
  approvedBy: string | null;
}

export interface DelegationAcknowledgment {
  id: string;
  agencyId: string;
  assignmentId: string;
  staffId: string;
  staffName: string;
  openedAt: string | null;
  signedAt: string | null;
  signatureName: string | null;
  signatureMark: string | null;
}

/** Per-staff acknowledgment rollup for one assignment (HM/DPM view). */
export interface DelegationAckStatusRow {
  staffId: string;
  staffName: string;
  openedAt: string | null;
  signedAt: string | null;
  overdue: boolean;
}

export function trainingMaterialStatusLabel(status: TrainingMaterialStatus): string {
  switch (status) {
    case "draft":
      return "Draft";
    case "in_review":
      return "In review";
    case "published":
      return "Published";
  }
}

export function delegationLifecycleLabel(assignment: {
  status: DelegationAssignmentStatus;
}): string {
  return assignment.status === "assigned" ? "In preparation" : "Ended";
}

/**
 * Pure helper: instantiate an editable training draft for one person from a
 * template. The draft starts as a copy of the generic sections with empty
 * individual notes for the DPM/RN to complete.
 */
export function instantiateDraft(
  template: DelegationTemplate,
  assignment: Pick<
    IndividualDelegationAssignment,
    "individualId" | "individualName" | "siteId" | "siteName"
  >,
): TrainingMaterialContent {
  return {
    templateId: template.id,
    templateName: template.name,
    individualId: assignment.individualId,
    individualName: assignment.individualName,
    siteId: assignment.siteId,
    siteName: assignment.siteName,
    purpose: template.sections.purpose,
    steps: [...template.sections.steps],
    safetyWarnings: [...template.sections.safetyWarnings],
    documentation: [...template.sections.documentation],
    individualNotes: "",
    individualizationNote: template.individualizationNote,
    generatedMark: DIGITAL_RECORD_MARK,
  };
}

/**
 * Pure helper: what training content a staff member may see. Reviewers
 * (delegation.training.review / approve) see the draft; ordinary site staff
 * see published content only — never the draft.
 */
export function visibleMaterialForStaff(
  material: DelegationTrainingMaterial,
  canReview: boolean,
): TrainingMaterialContent | null {
  if (canReview) return material.draftContent;
  if (material.status === "published") return material.publishedContent;
  return null;
}

/** ISO timestamp at which an acknowledgment becomes overdue. */
export function acknowledgmentDueAt(publishedAt: string): string {
  return new Date(
    Date.parse(publishedAt) + DELEGATION_ACK_DUE_DAYS * 24 * 60 * 60 * 1000,
  ).toISOString();
}

/** True when the staff member has not signed and the due window has passed. */
export function isAcknowledgmentOverdue(
  signedAt: string | null,
  publishedAt: string | null,
  now: number = Date.now(),
): boolean {
  if (signedAt) return false;
  if (!publishedAt) return false;
  return now > Date.parse(acknowledgmentDueAt(publishedAt));
}

/**
 * The common template library. Generic Complyrer-original starting material —
 * every entry requires individualization by the DPM/RN before approval.
 */
export const DELEGATION_TEMPLATES: Omit<DelegationTemplate, "id" | "agencyId">[] = [
  {
    name: "Bowel movement (BM) protocol",
    category: "Health monitoring",
    sections: {
      purpose:
        "Support regular bowel habits for the person by following their individualized bowel routine and noticing changes early.",
      steps: [
        "Follow the person's individualized bowel routine as written in their support plan.",
        "Offer fluids and movement opportunities throughout the day as the plan describes.",
        "Observe and note each bowel movement: time, amount, and consistency in plain words.",
        "Report right away if the person has pain, straining, blood, or no bowel movement for the number of days their plan names.",
        "Keep the bathroom routine calm, private, and respectful of the person's dignity.",
      ],
      safetyWarnings: [
        "Never give laxatives, suppositories, enemas, or any bowel medication unless the current physician order and delegation say so.",
        "Do not change the person's diet, fluids, or routine to 'fix' constipation on your own — report it instead.",
        "Treat any report of severe abdominal pain, vomiting, or blood as urgent and follow the person's emergency contacts.",
      ],
      documentation: [
        "Record each bowel movement on the person's bowel tracking log the same day.",
        "Note anything unusual (pain, straining, blood, missed days) and who you reported it to.",
      ],
    },
    individualizationNote:
      "The DPM or RN must fill in this person's normal pattern, what counts as a missed day for them, and their current physician orders before approval.",
    active: true,
  },
  {
    name: "Seizure protocol",
    category: "Health monitoring",
    sections: {
      purpose:
        "Keep the person safe during and after a seizure and capture accurate information for their medical team.",
      steps: [
        "Stay with the person. Note the exact time the seizure starts.",
        "Ease the person to the floor if they are not already there; place something soft under their head.",
        "Move hard or sharp objects away. Loosen anything tight around the neck.",
        "Do not put anything in the person's mouth. Do not hold them down.",
        "Time the seizure. When it ends, note the time and place the person on their side if they are sleepy or vomiting.",
        "Stay until the person is fully alert and oriented, then help them rest as their plan describes.",
      ],
      safetyWarnings: [
        "Call emergency services when the person's seizure plan says to — for example a seizure lasting longer than the plan's limit, repeated seizures, trouble breathing afterward, or injury.",
        "Never leave the person alone while they are confused or sleepy after a seizure.",
        "Do not offer food, drink, or medication until the person is fully alert and their plan allows it.",
      ],
      documentation: [
        "Complete a seizure record the same day: date, start and end times, what you observed before/during/after, and any injury.",
        "Report the seizure to the nurse and house manager per the person's plan.",
      ],
    },
    individualizationNote:
      "The DPM or RN must add this person's seizure type(s), emergency thresholds, rescue medication orders (if any), and who to call before approval.",
    active: true,
  },
  {
    name: "High-fiber/high-protein diet",
    category: "Nutrition",
    sections: {
      purpose:
        "Serve meals and snacks that match the person's prescribed high-fiber, high-protein eating pattern.",
      steps: [
        "Follow the person's meal plan or diet guide for what to serve at each meal and snack.",
        "Include the fiber and protein foods the plan lists; keep portions as the plan describes.",
        "Offer water with meals and between meals as the plan directs.",
        "If the person refuses foods or eats very little, offer the plan's alternatives and note the intake.",
        "Store and reheat food safely; check dates on prepared items.",
      ],
      safetyWarnings: [
        "Do not change the diet pattern, add supplements, or remove foods because of a preference or a rumor — follow the written plan.",
        "Report ongoing poor intake, vomiting, diarrhea, or sudden weight changes to the nurse.",
        "Follow the person's choking or swallowing precautions at every meal if they have any.",
      ],
      documentation: [
        "Record meal intake as the plan requires (for example: full, half, refused).",
        "Note substitutions offered and anything unusual about appetite or tolerance.",
      ],
    },
    individualizationNote:
      "The DPM or RN must attach this person's actual meal plan or diet guide, portion sizes, fluid goals, and any swallowing precautions before approval.",
    active: true,
  },
  {
    name: "Calorie intake tracking",
    category: "Nutrition",
    sections: {
      purpose:
        "Track what the person eats and drinks so the team can see whether their intake meets the plan's goals.",
      steps: [
        "Record every meal, snack, and drink the person has, with the amounts eaten.",
        "Use the same measuring words each time (cups, pieces, bites) so records can be compared.",
        "Note refused or missed meals and what was offered instead.",
        "Add up the day's intake in the way the person's tracking sheet describes.",
        "Share the completed log with the nurse or dietitian on the schedule the plan names.",
      ],
      safetyWarnings: [
        "Do not guess or fill in meals you did not observe — leave them blank and note why.",
        "Report a pattern of refused meals or a sudden drop in intake promptly rather than waiting for the next review.",
      ],
      documentation: [
        "Complete the intake log daily and keep it where the team can find it.",
        "Flag days that fell well above or below the plan's target and tell the nurse.",
      ],
    },
    individualizationNote:
      "The DPM or RN must set this person's daily targets, what counts as a full portion for them, and the review schedule before approval.",
    active: true,
  },
  {
    name: "Choking/aspiration protocol",
    category: "Safety",
    sections: {
      purpose:
        "Reduce choking risk at meals and respond correctly if the person chokes or shows signs of aspiration.",
      steps: [
        "Seat the person upright for meals as their plan describes and keep mealtimes calm and unhurried.",
        "Serve food in the sizes and textures the person's plan lists; never 'upgrade' textures on your own.",
        "Stay with the person while they eat. Watch for coughing, throat clearing, wet voice, or pocketing food.",
        "If the person cannot breathe, cough, or speak, follow your choking-response training and call emergency services.",
        "After any choking episode, keep the person calm, do not offer more food, and report it immediately.",
      ],
      safetyWarnings: [
        "Never change food textures, liquid thickness, or adaptive equipment without a written order from the qualified professional.",
        "Treat repeated coughing at meals, frequent throat clearing, or chest congestion after eating as warning signs — report them the same day.",
        "Do not perform abdominal thrusts or other emergency techniques unless you are trained and the situation calls for it.",
      ],
      documentation: [
        "Document every choking or aspiration-sign episode: time, what happened, what you did, and who you notified.",
        "Note ongoing mealtime observations the plan asks you to track.",
      ],
    },
    individualizationNote:
      "The DPM or RN must specify this person's diet texture, liquid consistency, positioning, supervision level, and emergency steps before approval.",
    active: true,
  },
  {
    name: "G-tube feeding support",
    category: "Nutrition",
    sections: {
      purpose:
        "Support the person's tube feeding routine safely and notice problems early.",
      steps: [
        "Wash your hands and prepare the feeding area before you begin.",
        "Follow the person's written feeding schedule: formula type, amount, rate, and flushes.",
        "Position the person as their plan describes during and after the feeding.",
        "Check the tube site at each feeding for redness, swelling, leakage, or pain and report changes.",
        "Keep the equipment clean per the plan's cleaning steps and store supplies as directed.",
      ],
      safetyWarnings: [
        "Only staff trained and delegated for this person's G-tube care may perform feedings — never hand the task to someone else.",
        "Stop and report immediately for a dislodged tube, vomiting during a feeding, breathing difficulty, or severe pain.",
        "Never change the formula, amount, rate, or schedule without a written physician order.",
      ],
      documentation: [
        "Log each feeding: time started and finished, amount given, flushes, and tolerance.",
        "Record tube-site checks and anything unusual, with who you reported it to.",
      ],
    },
    individualizationNote:
      "The DPM or RN must attach this person's current physician orders (formula, rate, schedule, flushes), positioning, and site-care steps before approval. Only delegated, trained staff may be assigned.",
    active: true,
  },
  {
    name: "Blood sugar monitoring",
    category: "Health monitoring",
    sections: {
      purpose:
        "Check the person's blood sugar on the schedule their plan sets and respond to readings as directed.",
      steps: [
        "Gather the person's meter and supplies; check that strips are not expired.",
        "Wash your hands and help the person wash theirs, then follow the meter's steps to take the reading.",
        "Record the reading right away with the date and time.",
        "Compare the reading to the person's target range and follow the plan's instructions for low or high readings.",
        "Report readings outside the target range as the plan directs.",
      ],
      safetyWarnings: [
        "Never adjust insulin or other diabetes medication on your own — only follow current written orders.",
        "Treat signs of low blood sugar (shakiness, sweating, confusion) as urgent and follow the person's low-blood-sugar plan immediately.",
        "Do not share meters, lancets, or strips between people.",
      ],
      documentation: [
        "Log every reading with date, time, and any symptoms the person reported.",
        "Note actions taken for out-of-range readings and who you notified.",
      ],
    },
    individualizationNote:
      "The DPM or RN must enter this person's testing schedule, target range, low/high response steps, and current medication orders before approval.",
    active: true,
  },
  {
    name: "Fall prevention",
    category: "Safety",
    sections: {
      purpose:
        "Reduce the person's risk of falling during daily routines and respond correctly when a fall happens.",
      steps: [
        "Keep the person's walking paths clear of clutter, cords, and wet spots.",
        "Make sure the person uses their prescribed mobility aids, footwear, and supports as the plan describes.",
        "Give the person enough time to move; offer a steady arm or standby help at the level the plan names.",
        "Check that bed, chair, and bathroom supports are in place before transfers.",
        "If the person falls, do not rush to lift them — check for injury, keep them comfortable, and call for help per the plan.",
      ],
      safetyWarnings: [
        "Report every fall the same day, even if the person says they feel fine — some injuries appear later.",
        "Do not change mobility aids, transfer techniques, or supervision levels without the qualified professional's direction.",
        "Treat head strikes, loss of consciousness, or inability to bear weight after a fall as urgent.",
      ],
      documentation: [
        "Complete a fall report for every fall: time, place, what happened, injuries, and witnesses.",
        "Note near-falls and hazards you fixed so the team can adjust the plan.",
      ],
    },
    individualizationNote:
      "The DPM or RN must describe this person's mobility level, aids, transfer method, supervision needs, and post-fall steps before approval.",
    active: true,
  },
];
