import { test } from "node:test";
import assert from "node:assert/strict";
import {
  appointmentChangeDetail,
  canEditAllergies,
  canManageAppointments,
  canSeeAppointments,
  formatAppointmentWhen,
  formatGeneratedBy,
  formatLoggedBy,
  formatUpdatedBy,
  validateAppointmentDraft,
  visibleAppointments,
  type Appointment,
} from "./appointments";

const sample: Appointment = {
  id: "appt-1",
  agencyId: "a1",
  individualId: "i1",
  startsOn: "2026-09-22",
  startTime: "09:30",
  endTime: "10:15",
  timezone: "America/Chicago",
  consultant: "Dr. Priya Shah",
  specialty: "Neurology",
  reason: "Follow-up",
  visitAddress: "3201 Pompey Drive",
  createdBy: "u-rn",
  createdByName: "Cameron Price",
  createdAt: "2026-09-10T14:00:00.000Z",
  updatedBy: "",
  updatedByName: "",
  updatedAt: "2026-09-10T14:00:00.000Z",
  deletedBy: "",
  deletedByName: "",
  deletedAt: null,
};

test("RN and house manager can manage appointments; DSP cannot", () => {
  assert.equal(canManageAppointments("nurse"), true);
  assert.equal(canManageAppointments("house_manager"), true);
  assert.equal(canManageAppointments("administrator"), true);
  assert.equal(canManageAppointments("program_manager"), true);
  assert.equal(canManageAppointments("dsp"), false);
  assert.equal(canManageAppointments("auditor"), false);
  assert.equal(canManageAppointments("hr"), false);
  assert.equal(canEditAllergies("nurse"), true);
  assert.equal(canEditAllergies("dsp"), false);
});

test("assigned DSP can still view appointments", () => {
  assert.equal(canSeeAppointments("dsp"), true);
  assert.equal(canSeeAppointments("nurse"), true);
});

test("appointment draft requires consultant and a real time window", () => {
  const valid = validateAppointmentDraft({
    startsOn: "2026-09-22",
    startTime: "09:30",
    endTime: "10:15",
    timezone: "America/Chicago",
    consultant: "Dr. Priya Shah",
  });
  assert.equal(valid.consultant, "Dr. Priya Shah");
  assert.equal(valid.specialty, "");
  assert.throws(
    () =>
      validateAppointmentDraft({
        startsOn: "2026-09-22",
        startTime: "10:15",
        endTime: "09:30",
        timezone: "America/Chicago",
        consultant: "Dr. Priya Shah",
      }),
    /End time/,
  );
  assert.throws(
    () =>
      validateAppointmentDraft({
        startsOn: "2026-09-22",
        startTime: "09:30",
        endTime: "10:15",
        timezone: "America/Chicago",
        consultant: "  ",
      }),
    /consultant/,
  );
});

test("appointment when-label is human readable", () => {
  assert.equal(
    formatAppointmentWhen({
      startsOn: "2026-09-22",
      startTime: "09:30",
      endTime: "10:15",
      timezone: "America/Chicago",
    }),
    "September 22, 2026 · 9:30 AM–10:15 AM · America/Chicago",
  );
});

test("who/when stamps use the logged/updated/generated copy", () => {
  assert.equal(
    formatLoggedBy("Cameron Price", "2026-09-10T14:00:00.000Z"),
    "Logged by Cameron Price · September 10, 2026, 9:00 AM",
  );
  assert.equal(
    formatUpdatedBy("Sarah Mitchell", "2026-09-12T16:30:00.000Z"),
    "Updated by Sarah Mitchell · September 12, 2026, 11:30 AM",
  );
  assert.equal(
    formatGeneratedBy("Alex Morgan", "2026-09-12T18:00:00.000Z"),
    "Generated by Alex Morgan · September 12, 2026, 1:00 PM",
  );
});

test("DSP does not see soft-deleted appointments; RN still does", () => {
  const removed: Appointment = {
    ...sample,
    id: "appt-2",
    deletedAt: "2026-09-11T15:00:00.000Z",
    deletedBy: "u-rn",
    deletedByName: "Cameron Price",
  };
  const dspView = visibleAppointments([sample, removed], false);
  assert.deepEqual(
    dspView.map((row) => row.id),
    ["appt-1"],
  );
  const rnView = visibleAppointments([sample, removed], true);
  assert.equal(rnView.length, 2);
});

test("appointment audit detail lists from → to without rewriting the author", () => {
  const detail = appointmentChangeDetail(sample, {
    startsOn: "2026-09-22",
    startTime: "09:30",
    endTime: "11:00",
    timezone: "America/Chicago",
    consultant: "Dr. Priya Shah",
    specialty: "Neurology",
    reason: "Med review",
    visitAddress: "3201 Pompey Drive",
  });
  assert.ok(detail.includes("End: 10:15 → 11:00"));
  assert.ok(detail.includes("Reason: Follow-up → Med review"));
  assert.ok(!detail.includes("Consultant:"));
});
